import {eq} from './arrigo-content.mjs';
import {tex} from './math.mjs';
const mi=s=>`<mi>${s}</mi>`,mn=s=>`<mn>${s}</mn>`,mo=s=>`<mo>${s}</mo>`,row=s=>`<mrow>${s}</mrow>`,sup=(s,p)=>`<msup>${mi(s)}${mn(p)}</msup>`,frac=(a,b)=>`<mfrac>${row(a)}${row(b)}</mfrac>`;
const text=s=>`<mtext>${s}</mtext>`;
const lines=rows=>`<mtable columnalign="left" rowspacing="0.5em">${rows.map(s=>`<mtr><mtd>${s}</mtd></mtr>`).join('')}</mtable>`;
const displayFormulae={
 'Gamma igual xi por derivada parcial en x más eta por derivada parcial en y':String.raw`\Gamma=\xi\frac{\partial}{\partial x}+\eta\frac{\partial}{\partial y}`,
 'Gamma r cero y Gamma s uno':String.raw`\Gamma r=0,\qquad \Gamma s=1`,
 'Condición de invariancia de Lie':String.raw`\begin{aligned}&\eta_x+(\eta_y-\xi_x)F\\&\quad-\xi_yF^2-\xi F_x-\eta F_y=0\end{aligned}`,
 'Factor integrante y ecuación reducida lineal':String.raw`\mu=e^{\int P(x)\,\mathrm{d}x},\qquad \frac{\mathrm{d}s}{\mathrm{d}r}=\mu Q`,
 's menos uno sobre dos x cuadrado y cuadrado; derivada uno sobre x':String.raw`s=-\frac{1}{2x^2y^2},\qquad\frac{\mathrm{d}s}{\mathrm{d}x}=\frac1x`,
 'Derivada de r respecto a s igual F de r menos r':String.raw`\frac{\mathrm{d}r}{\mathrm{d}s}=F(r)-r`,
 'Factor integrante uno sobre M xi más N eta; potencial un décimo logaritmo de valor absoluto de I':String.raw`\mu=\frac{1}{M\xi+N\eta},\qquad\Phi=\frac1{10}\ln|I|`,
 'Recíproco de y menos solución particular y ecuación lineal':String.raw`w=\frac{1}{y-y_1},\qquad w'+Aw=-P`,
 'Recurrencia de prolongación':String.raw`\eta^{(k)}=D_x\eta^{(k-1)}-y^{(k)}D_x\xi`,
 'Segunda prolongación expandida':String.raw`\begin{aligned}\eta^{(2)}={}&\eta_{xx}+(2\eta_{xy}-\xi_{xx})p\\&+(\eta_{yy}-2\xi_{xy})p^2-\xi_{yy}p^3\\&+(\eta_y-2\xi_x)q-3\xi_y pq\end{aligned}`,
 'Segunda ecuación no lineal reducida a segunda derivada de s igual uno':String.raw`y''+3yy'+y^3=0\quad\Longrightarrow\quad\frac{\mathrm{d}^2s}{\mathrm{d}r^2}=1`,
 'Reducción autónoma de Blasius':String.raw`\begin{gathered}y'''+yy''=0\\ r=y,\quad v(r)=y'\\ v v_{rr}+v_r^2+r v_r=0\end{gathered}`,
 'Generador de escala del sistema y variables desacopladas':String.raw`\begin{gathered}\Gamma=t\partial_t-x\partial_x-y\partial_y\\\dot U=U^2,\qquad\dot V=V^2\end{gathered}`,
 'Momento angular, ecuación radial y energía':String.raw`\begin{aligned}L&=u^2 v'\\u''&=\frac{L^2+1}{u^3}\\E&=\frac{(u')^2}{2}+\frac{L^2+1}{2u^2}\end{aligned}`
};
const formula=(s,label)=>displayFormulae[label]?tex(displayFormulae[label],true):eq(s,label);
// The shared renderer handles powers without rewriting HTML attributes or TeX.
export const inlineMath=s=>s;
const steps=items=>`<ol class="math-steps">${items.map(([h,p])=>`<li><h3>${h}</h3><p>${inlineMath(p)}</p></li>`).join('')}</ol>`;
const aside=(title,s)=>`<div class="insight"><span class="insight-symbol">∴</span><p><strong>${title}</strong>${inlineMath(s)}</p></div>`;
const more=(title,s)=>`<details class="extension"><summary>${title}</summary><div class="detail-body">${inlineMath(s)}</div></details>`;
const note=(intro,items,math,extra)=>`<p>${intro}</p>${math}${steps(items)}${extra}`;
export const arrigo2Lessons=[
 {title:'Infinitesimales y coordenadas canónicas',nav:'Del generador al flujo',reference:'2.1',pages:'15–23',desc:'Un campo vectorial genera el movimiento completo. Busca una coordenada fija y otra que avance con ε.'},
 {title:'La condición de invariancia de Lie',nav:'Encontrar una simetría',reference:'2.2',pages:'23–28',desc:'Transforma también la pendiente: una identidad diferencial decide qué generadores preservan la EDO.'},
 {title:'Ecuaciones lineales',nav:'Lineales',reference:'2.3.1',pages:'28–30',desc:'El factor integrante convierte la simetría en una traslación de la constante de integración.'},
 {title:'Ecuaciones de Bernoulli',nav:'Bernoulli',reference:'2.3.2',pages:'30–31',desc:'Una potencia de y linealiza la ecuación. Comprueba dónde la transformación deja de existir.'},
 {title:'Ecuaciones homogéneas',nav:'Homogéneas',reference:'2.3.3',pages:'31–32',desc:'La razón y/x elimina la escala. Las raíces del campo reducido recuperan soluciones que una división oculta.'},
 {title:'Exactitud y factores integrantes',nav:'Exactas',reference:'2.3.4',pages:'32–35',desc:'Una simetría permite construir un factor integrante. Distingue una integral primera de un invariante del grupo.'},
 {title:'Riccati y una solución particular',nav:'Riccati',reference:'2.3.5',pages:'35–38',desc:'Desplaza la solución conocida y toma su recíproco: la no linealidad se transforma en una ecuación lineal.'},
 {title:'Operadores y prolongaciones',nav:'Prolongar el generador',reference:'2.4',pages:'38–43',desc:'Las derivadas viven en el espacio de jets. La derivada total prolonga el movimiento a cualquier orden.'},
 {title:'Simetrías de segundo orden',nav:'Segundo orden',reference:'2.5',pages:'43–56',desc:'Reduce el orden de una EDO. Compara una recta, una ecuación con escala y una no lineal que se vuelve s″=1.'},
 {title:'Orden superior: la ecuación de Blasius',nav:'Blasius',reference:'2.6',pages:'56–61',desc:'Una simetría de traslación baja el orden. Explora el perfil y resuelve numéricamente su condición lejana.'},
 {title:'Sistemas de primer orden',nav:'Sistemas',reference:'2.7.1',pages:'61–67',desc:'Transforma el tiempo y las dos variables dependientes. Un cambio de variables desacopla el ejemplo del libro.'},
 {title:'Sistemas de segundo orden y fuerza central',nav:'Fuerza central',reference:'2.7.2',pages:'67–72',desc:'La rotación lleva a coordenadas polares. El momento angular reduce el sistema a una ecuación radial.'}
];
export const arrigo2Notes=[
 note('El capítulo 1 suponía que conocíamos una transformación. Ahora buscamos su velocidad en ε=0. Escribimos ξ y η para los infinitesimales que Arrigo llama X e Y; así evitamos confundirlos con las coordenadas transformadas.',[
 ['Linealiza cerca de la identidad','x̄=x+εξ(x,y)+O(ε²), ȳ=y+εη(x,y)+O(ε²). El operador Γ actúa sobre una función como su derivada direccional. Una simetría no necesita fijar los puntos ni una solución concreta: mueve curvas solución a otras curvas solución.'],
 ['Reconstruye el movimiento','Integra dx̄/dε=ξ(x̄,ȳ), dȳ/dε=η(x̄,ȳ) con condición inicial (x,y). El campo se evalúa en el punto que va moviéndose. Por ejemplo, Γ=∂x+2x∂y produce x̄=x+ε, ȳ=y+2xε+ε²: el término cuadrático se pierde en la aproximación tangente.'],
 ['Elige coordenadas adaptadas','Resuelve Γr=0 y Γs=1. Las características dy/dx=η/ξ encuentran r; luego integra una coordenada a lo largo del flujo para obtener s. Exige un jacobiano no nulo. Para Γ=x∂x−y∂y sirven r=xy, s=ln|x|, en una carta con x≠0.'],
 ['Comprueba la reducción','En y′=y²−y/x−1/x², dr/dx=(r²−1)/x y ds/dx=1/x. Por tanto ds/dr=1/(r²−1). La integral es ½ln|(r−1)/(r+1)|+C. Si r=±1, vuelve a la EDO: aparecen y=±1/x.'],
 ['Comprende el carácter local','Una rotación admite s=atan2(y,x) solo en una carta angular: no hay una coordenada real continua s en toda la circunferencia. Un flujo racional termina al alcanzar un polo. Γ=0 tampoco puede satisfacer Γs=1 en ese punto.']
 ],formula(mi('Γ')+mo('=')+mi('ξ')+frac(text('∂'),text('∂x'))+mo('+')+mi('η')+frac(text('∂'),text('∂y')),'Gamma igual xi por derivada parcial en x más eta por derivada parcial en y')+formula(mi('Γr')+mo('=')+mn('0')+mo(',')+mi('Γs')+mo('=')+mn('1'),'Gamma r cero y Gamma s uno'),
 aside('Correcciones de lectura.','En la p. 16, (2.4) debe tener r²−1 en el denominador. En la reducción por recíprocos de la p. 17, el denominador es r²+2r+2. Ambas expresiones se obtienen sustituyendo en la EDO, no por una elección de constante.')+more('Ejercicio guiado: libertad de elección','<p>Si (r,s) son canónicas, también lo son (R(r), s+S(r)) cuando R′≠0. ΓR=R′Γr=0 y Γ(s+S)=1. Elige R(r)=2r y S(r)=r² para comprobarlo; luego explica por qué R constante deja de ser un cambio de coordenadas.</p>')),
 note('Una transformación de (x,y) transforma también y′. La condición de Lie expresa la coincidencia entre esa pendiente transformada y la pendiente que exige la ecuación en el nuevo punto.',[
 ['Prolonga una vez','Pon p=y′. Por la regla de la cadena, la velocidad de p es η⁽¹⁾=ηₓ+(ηᵧ−ξₓ)p−ξᵧp². El término −ξᵧp² aparece porque también cambia la variable independiente.'],
 ['Restringe a la ecuación','Para Δ=p−F(x,y), calcula Γ⁽¹⁾Δ y después sustituye p=F. Queda ηₓ+(ηᵧ−ξₓ)F−ξᵧF²−ξFₓ−ηFᵧ=0. Debe ser una identidad en un dominio abierto, no solo en un punto.'],
 ['Encuentra pesos, no los adivines','En F=xy³ prueba ξ=ax, η=by. El residuo es −2(a+b)xy³. Por tanto b=−a. El laboratorio permite modificar los pesos y ver por qué una dilatación con a=b falla salvo casos puntuales.'],
 ['Usa un ansatz con honestidad','El libro ensaya ξ=A(x), η=B(x)y para F=y/x+x²/(x+y). Tras separar potencias de y resulta B=A′+A/x, A″=0 y A′=0. Se obtiene A=c, B=c/x. Esto encuentra una familia dentro del ansatz; no demuestra que sean todas las simetrías posibles.'],
 ['Comprueba que la reducción sea útil','La característica η−ξF mide si Γ cruza las curvas solución. Un campo tangente a ellas puede satisfacer Lie, pero entonces la coordenada invariante queda constante a lo largo de cada solución y no sirve para parametrizarla como s(r).']
 ],formula(lines([text('ηₓ + (ηᵧ−ξₓ)F'),text('− ξᵧF² − ξFₓ − ηFᵧ = 0')]),'Condición de invariancia de Lie'),
 aside('Errata en la p. 26.','El cierre del ejemplo 2.11 imprime Y=cx/y. Como Y=B(x)y y B=c/x, la expresión correcta es Y=cy/x. Sustituirla en la condición de Lie confirma la identidad.')+more('Ejercicio guiado: traslación vertical','<p>Prueba Γ=∂y: ξ=0, η=1. Todos sus derivados son cero, así que el residuo es −Fᵧ. La traslación vertical es simetría si F no depende de y. Para y′=xy³ falla; en y=0 el residuo puntual es cero, pero eso no prueba una identidad.</p>')),
 note('La simetría de una EDO lineal consiste en sumar una solución de su ecuación homogénea. El factor integrante convierte esa suma variable en una traslación constante.',[
 ['Construye el factor integrante','Para y′+P(x)y=Q(x), toma μ=e^{∫P dx}. Entonces (μy)′=μQ. Una constante multiplicativa no nula en μ solo cambia la normalización.'],
 ['Lee el generador','Busca ξ=0, η=η(x). Lie exige η′+Pη=0, así que η=1/μ. El flujo es x̄=x, ȳ=y+ε/μ(x); no es una traslación vertical uniforme cuando P varía o es distinto de cero.'],
 ['Adapta las coordenadas','r=x y s=μy satisfacen Γr=0, Γs=1. La ecuación reducida s′=μQ ya no contiene s. Integra y divide por μ para regresar.'],
 ['Resuelve el ejemplo','En y′+y=x, μ=eˣ y s=eˣ(x−1)+C. Por tanto y=x−1+Ce⁻ˣ. Aplicar el flujo cambia C a C+ε. Dos soluciones se acercan como e⁻ˣ, aunque su separación en s sea constante.'],
 ['Generaliza el laboratorio','Para P=λ>0, Q=x, y=x/λ−1/λ²+Ce^{−λx}. Derivando obtienes y′+λy=x. El parámetro λ cambia la EDO; ε transforma soluciones de la EDO con λ fijo.']
 ],formula(mi('μ')+mo('=')+`<msup><mi>e</mi><mrow><mo>∫</mo><mi>P</mi><mi>dx</mi></mrow></msup>`+mo(',')+frac(text('ds'),text('dr'))+mo('=')+mi('μQ'),'Factor integrante y ecuación reducida lineal'),
 more('Práctica resuelta: una condición inicial','<p>Si y(0)=2 en y′+y=x, entonces −1+C=2 y C=3. Después del flujo ε, la condición inicial pasa a ȳ(0)=2+ε. La ecuación permanece igual, pero una condición inicial fija normalmente selecciona una única curva.</p>')),
 note('Bernoulli es no lineal en y, pero una potencia adecuada la vuelve lineal. Las simetrías explican por qué funciona esta sustitución y obligan a revisar sus dominios.',[
 ['Identifica la potencia','En y′+P(x)y=Q(x)yⁿ, n≠0,1, toma z=y^{1−n} en una rama real donde esté definida. Multiplica la EDO por (1−n)y⁻ⁿ: z′+(1−n)Pz=(1−n)Q. Los casos n=0 y n=1 son ya lineales.'],
 ['Encuentra las coordenadas canónicas','El generador es Γ=e^{(n−1)∫P dx}yⁿ∂y. Con r=x y s=e^{−(n−1)∫P dx}y^{1−n}/(1−n), se obtiene ds/dr=Qe^{−(n−1)∫P dx}.'],
 ['Trabaja el ejemplo cúbico','Para y′+y/x=xy³, x>0, Γ=x²y³∂y. Elige s=−1/(2x²y²). Al derivar, s′=x⁻³y⁻²+x⁻²y⁻³y′=1/x. Así s=ln x+C.'],
 ['Reconstruye las ramas','y=±1/[x√(−2(ln x+C))]. Necesitas ln x+C<0. El flujo ȳ=y/√(1−2εx²y²) conserva el signo de la rama y exige un denominador positivo en el recorrido desde ε=0.'],
 ['Recupera lo que dividiste','y=0 resuelve la EDO original y no aparece en s. El laboratorio incluye esta solución como caso separado. En la carta x<0 se usa ln|x| y se comprueba de nuevo la elección de la rama.']
 ],formula(mi('s')+mo('=')+mo('−')+frac(mn('1'),mn('2')+sup('x','2')+sup('y','2'))+mo(',')+frac(text('ds'),text('dx'))+mo('=')+frac(mn('1'),mi('x')),'s menos uno sobre dos x cuadrado y cuadrado; derivada uno sobre x'),
 aside('Errata en la p. 31.','El ejemplo 2.13 imprime −1/(4r). La derivación anterior da 1/r para las coordenadas indicadas; el laboratorio usa esta expresión corregida.')+more('Ejercicio guiado: qué hace ε','<p>Como s̄=s+ε, la constante pasa de C a C+ε. Si ε llega a −ln x−C en un punto, su imagen se hace infinita. El mapa es local: no continúes la rama real atravesando ese valor.</p>')),
 note('Una EDO homogénea de primer orden tiene y′=F(y/x). “Homogénea” aquí se refiere a la invariancia de escala; no significa que sea una ecuación lineal con término independiente cero.',[
 ['Elimina la escala común','El flujo (x̄,ȳ)=(eᵋx,eᵋy) conserva r=y/x. En x≠0, s=ln|x| avanza en ε. Con y=xr, y′=r+dr/ds.'],
 ['Reduce sin perder equilibrios','La forma segura es dr/ds=F(r)−r. Solo donde F(r)−r≠0 puedes invertir y escribir ds/dr=1/[F(r)−r]. Cada raíz r₀ da la solución recta y=r₀x y debe guardarse antes de dividir.'],
 ['Integra el ejemplo del libro','Para y′=(y+√(x²+y²))/x, en x>0, F(r)=r+√(1+r²). Así s′=1/√(1+r²), s=asinh(r)+C. Reconstruye x=eˢ, y=rx. La dilatación desplaza C.'],
 ['Respeta el signo de x','En x<0, √(x²+y²)/x=−√(1+r²). La ecuación reducida cambia de signo. La expresión del laboratorio representa expresamente la carta x>0.'],
 ['Observa una solución perdida','El segundo modelo, y′=r+r²−1, tiene dr/ds=r²−1. Las rectas y=±x son soluciones. Las demás ramas tienen s=½ln|(r−1)/(r+1)|+C; el laboratorio permite ver las rectas aparte.']
 ],formula(frac(text('dr'),text('ds'))+mo('=')+mi('F')+mo('(')+mi('r')+mo(')')+mo('−')+mi('r'),'Derivada de r respecto a s igual F de r menos r'),
 more('Ejercicio resuelto: y′=2y/x','<p>F(r)=2r, de modo que dr/ds=r. Entonces r=Keˢ y, en x>0, y=Kx². La raíz r=0 produce y=0. Si hubieras dividido por r, la constante K=0 requeriría una comprobación aparte.</p>')),
 note('La forma M dx+N dy=0 es exacta cuando existe una función Φ con Φₓ=M, Φᵧ=N. En un dominio local apropiado, Mᵧ=Nₓ permite construirla. Una simetría ofrece un factor integrante sin resolver primero la EDO.',[
 ['Comprueba la exactitud original','En el ejemplo M=2x⁴y+y⁴, N=x⁵−2xy³. Mᵧ−Nₓ=−3x⁴+6y³, que no es idénticamente cero. No basta con que se anule en una curva.'],
 ['Usa el generador ponderado','Γ=3x∂x+4y∂y es una simetría. La contracción Mξ+Nη=5xy(2x⁴−y³). Donde no sea cero, μ=1/(Mξ+Nη) convierte μM dx+μN dy en una forma cerrada. La fórmula supone una simetría de la EDO y un campo transversal a sus soluciones.'],
 ['Integra la forma','Una primitiva es Φ=(1/10)ln|I|, donde I=y(2x⁴−y³)/x². Deriva Φ en x e y para comprobar Φₓ=μM y Φᵧ=μN. Las curvas solución satisfacen I=K, con signo fijo en cada carta.'],
 ['Distingue dos conservaciones','I es constante a lo largo de una solución, pero ΓI=10I. El flujo x̄=e^{3ε}x, ȳ=e^{4ε}y lleva K a e^{10ε}K. En cambio ΓΦ=1. Una integral primera de la EDO no tiene por qué ser un invariante del grupo.'],
 ['Revisa las singularidades del factor','μ excluye x=0, y=0 y 2x⁴=y³. Para x≠0, y=0 y y=2^{1/3}|x|^{4/3} resuelven la forma original y se recuperan como K=0. N=0 puede representar una tangente vertical: la forma diferencial sigue teniendo sentido aunque y′=−M/N no.']
 ],formula(mi('μ')+mo('=')+frac(mn('1'),mi('Mξ')+mo('+')+mi('Nη'))+mo(',')+mi('Φ')+mo('=')+frac(mn('1'),mn('10'))+text(' ln|I|'),'Factor integrante uno sobre M xi más N eta; potencial un décimo logaritmo de valor absoluto de I'),
 aside('Lectura de las pp. 34–35.','En la p. 34, la definición de M omite el factor y que sí aparece en (2.73): M=2x⁴y+y⁴. Al integrar, el libro absorbe el factor constante 5 del denominador de μ y escribe Φ=(1/2)ln|I|. Aquí mantenemos μ=1/(Mξ+Nη), por lo que Φ=(1/10)ln|I| y ΓΦ=1. Ambas normalizaciones dan las mismas curvas I=K.')+more('Ejercicio guiado: factores no únicos','<p>Si μω=dΦ, entonces f(Φ)μω=dH(Φ), donde H′=f. Hay muchos factores integrantes. La exactitud es local; en un dominio con agujeros, una forma cerrada no tiene por qué admitir una primitiva global.</p>')),
 note('Para una Riccati y′=P(x)y²+Q(x)y+R(x), conocer una solución particular y₁ abre la puerta a una ecuación lineal. Encontrar y₁ puede seguir siendo la parte difícil.',[
 ['Desplaza la solución conocida','Pon q=y−y₁ y A=2Py₁+Q. Como y₁ satisface la EDO, q′=Aq+Pq². El término independiente desaparece.'],
 ['Toma el recíproco','Para q≠0, w=1/q cumple w′+Aw=−P. Es una ecuación lineal. La solución q=0, es decir y=y₁, queda fuera de esta sustitución y debe conservarse.'],
 ['Reconoce la simetría','Define H=e^{−∫A dx}. El generador vertical es Γ=Hq²∂y. Con r=x, s=−1/(Hq), resulta ds/dr=P/H. El flujo es q̄=q/(1−εHq) y desplaza s en ε.'],
 ['Resuelve el ejemplo del capítulo','y′=e⁻ˣy²+2y−2eˣ tiene y₁=eˣ. Aquí A=4, H=e⁻⁴ˣ y s′=e³ˣ. De s=e³ˣ/3+C se obtiene y=eˣ−e⁴ˣ/(e³ˣ/3+C).'],
 ['Comprueba ramas y polos','El denominador e³ˣ/3+C puede anularse para C<0. Una solución se estudia en un intervalo sin polos. El laboratorio usa C>0 y ofrece por separado y₁. El flujo exige 1−εHq>0 en el componente conectado a la identidad.']
 ],formula(mi('w')+mo('=')+frac(mn('1'),mi('y')+mo('−')+mi('y₁'))+mo(',')+text('w′ + Aw = −P'),'Recíproco de y menos solución particular y ecuación lineal'),
 more('Práctica resuelta: verifica y₁','<p>Sustituye y=eˣ: e⁻ˣe²ˣ+2eˣ−2eˣ=eˣ=y′. Si eligieras y₁=0, el término −2eˣ no desaparecería; la reducción basada en una “particular” incorrecta fallaría.</p>')),
 note('Una ecuación de orden n relaciona x,y y sus derivadas hasta y⁽ⁿ⁾. El espacio de jets guarda esas derivadas como coordenadas independientes antes de imponer la ecuación.',[
 ['Distingue parcial y total','Dₓ=∂x+p∂y+q∂p+z∂q+⋯, con p=y′, q=y″, z=y‴. Al derivar una función a lo largo de una curva, también varían y,p,q. Por ejemplo Dₓ(xy)=y+xp.'],
 ['Prolonga por recurrencia',`Parte de η⁽⁰⁾=η. Para k≥1, η⁽ᵏ⁾=Dₓη⁽ᵏ⁻¹⁾−y⁽ᵏ⁾Dₓξ. El término final corrige el cambio de la variable independiente. ${tex(String.raw`\Gamma^{(n)}=\Gamma+\sum_{k=1}^{n}\eta^{(k)}\frac{\partial}{\partial y^{(k)}}`)}.`],
 ['Comprueba la escala','Para ξ=ax, η=by, η⁽ᵏ⁾=(b−ka)y⁽ᵏ⁾. El flujo finito da ȳ⁽ᵏ⁾=e^{(b−ka)ε}y⁽ᵏ⁾. Cada derivación resta un peso a. No todas las derivadas cambian como y.'],
 ['Ensaya un movimiento menos trivial','Para Γ=y∂x, η⁽¹⁾=−p², η⁽²⁾=−3pq y η⁽³⁾=−4pz−3q². El flujo x̄=x+εy, ȳ=y requiere 1+εp≠0 para mantener x̄ como variable independiente local.'],
 ['Aplica la condición al orden adecuado','Si Δ=y″−F(x,y,p), exige Γ⁽²⁾Δ=0 después de sustituir y″=F. No pongas p=F: esa sustitución corresponde a primer orden. Separar potencias de p genera las ecuaciones determinantes.']
 ],formula(text('η⁽ᵏ⁾')+mo('=')+text('Dₓη⁽ᵏ⁻¹⁾')+mo('−')+text('y⁽ᵏ⁾Dₓξ'),'Recurrencia de prolongación')+formula(lines([text('η⁽²⁾ = ηₓₓ+(2ηₓᵧ−ξₓₓ)p'),text('+(ηᵧᵧ−2ξₓᵧ)p²−ξᵧᵧp³'),text('+(ηᵧ−2ξₓ)q−3ξᵧpq')]),'Segunda prolongación expandida'),
 aside('Lectura de la p. 42.','La expresión expandida presenta errores de signo y potencia. La recurrencia anterior y la fórmula de (2.91), p. 44, dan el término +(ηᵧ−2ξₓ)q y el factor p² mostrados aquí.')+more('Ejercicio resuelto: traslación de y','<p>Para Γ=∂y, ξ=0 y η=1: η⁽¹⁾=η⁽²⁾=⋯=0. Sumar una constante a y no cambia ninguna derivada. Una EDO de orden n conserva esta simetría si su expresión no depende explícitamente de y.</p>')),
 note('Una simetría de una EDO de segundo orden puede convertirla en otra de primer orden. El capítulo compara tres ejemplos; sus reducciones no tienen todas la misma dificultad.',[
 ['La referencia: y″=0','En la condición prolongada, los coeficientes de 1,p,p²,p³ dan ηₓₓ=0, 2ηₓᵧ−ξₓₓ=0, ηᵧᵧ−2ξₓᵧ=0 y ξᵧᵧ=0. Hay ocho parámetros: ξ=(a₁x+a₂)y+p₁x²+b₁x+b₂; η=a₁y²+(p₁x+p₂)y+q₁x+q₂. El laboratorio transforma rectas mediante ȳ=y+εx; ȳ=y+εx² es un contraejemplo.'],
 ['Una reducción con escala','y″+yy′+xy⁴=0 admite Γ=x∂x−y∂y. Con r=xy, s=ln x y p=ds/dr, la EDO queda p′=(r⁴−r²+2r)p³+(r−3)p². Se ha reducido el orden; no se ha encontrado automáticamente una integral elemental. El laboratorio integra la EDO original numéricamente y verifica la escala de sus términos.'],
 ['La no lineal que se simplifica','En y″+3yy′+y³=0, usa Γ₁=y∂x−y³∂y. Las coordenadas r=x−1/y y s=1/(2y²) dan d²s/dr²=1. Integra: s=r²/2+Ar+B. El movimiento finito es ȳ=y/√(1+2εy²), x̄=x+(√(1+2εy²)−1)/y.'],
 ['Reconstruye y comprueba','Otra vía toma y=u′/u: y″+3yy′+y³=u‴/u. Así u=ax²+bx+c y y=(2ax+b)/(ax²+bx+c). Multiplicar a,b,c por una misma constante no cambia y. Evita las raíces de u. Esta familia incluye y=0 y y=1/(x+c), que requieren revisión cuando las coordenadas canónicas se vuelven singulares.'],
 ['Vigila la parametrización','En la carta de Γ₁ necesitas y≠0 y dr/dx≠0. Para y=1/(x+c), r es constante. La curva no puede escribirse como s(r), aunque sí sea solución. Elegir otra simetría puede evitar una mala carta.']
 ],formula(text('y″+3yy′+y³')+mo('=')+mn('0')+mo('⇒')+frac(text('d²s'),text('dr²'))+mo('=')+mn('1'),'Segunda ecuación no lineal reducida a segunda derivada de s igual uno'),
 more('Las otras elecciones del libro','<p>La misma EDO tiene ocho generadores. Una base es Γ₁=y∂x−y³∂y; Γ₂=xy∂x+(y²−xy³)∂y; Γ₃=x²y∂x+(−x²y³+2xy²−2y)∂y; Γ₄=x³y∂x+(−x³y³+3x²y²−6xy+4)∂y; Γ₅=(x⁴y−2x³)∂x+(−x⁴y³+4x³y²−6x²y+4x)∂y; Γ₆=∂x; Γ₇=x∂x−y∂y; Γ₈=x²∂x+(2−2xy)∂y. Se obtienen de las constantes en (2.120)–(2.122).</p><p>Γ₂ permite r=x/y−x²/2, s=x−1/y y s″=0. Para Γ₆ usa r=y,s=x: si p=ds/dr, p′=r³p³+3rp². Para Γ₇, r=xy,s=ln x: p′=(r−1)(r²−2r)p³+3(r−1)p². Son descripciones locales distintas de las mismas curvas.</p>')),
 note('El método de prolongación se extiende a cualquier orden. El ejemplo físico del capítulo es la ecuación de Blasius en la normalización y‴+yy″=0; usamos exactamente esa normalización.',[
 ['Encuentra las simetrías','La condición de tercer orden deja Γ=(c₁x+c₂)∂x−c₁y∂y. Sus dos generadores básicos son ∂x y x∂x−y∂y. Para este último, y‴ e yy″ tienen ambos peso −4; el cero de la ecuación se conserva.'],
 ['Reduce mediante autonomía','Como x no aparece explícitamente, toma r=y y v(r)=y′, donde y′≠0. Entonces y″=v vᵣ y y‴=v(vᵣ²+v vᵣᵣ). Tras dividir por v, queda v vᵣᵣ+vᵣ²+r vᵣ=0: tercer orden pasa a segundo. Reconstruye x mediante dx/dr=1/v.'],
 ['No fuerces la carta en la pared','El perfil de interés tiene y(0)=y′(0)=0. Justo allí v=0 y no puedes dividir ni usar y como variable independiente. El laboratorio integra el sistema original y′=p, p′=q, q′=−yq con q(0)=a.'],
 ['Usa el disparo numérico','Prueba a, integra hasta x=8 y compara y′(8) con 1. El botón ajusta a por bisección. “Hasta 8” aproxima la condición lejana; no es una igualdad demostrada en infinito. El paso de Runge–Kutta se controla y se verifica por refinamiento.'],
 ['Separa EDO y condiciones de contorno','La escala transforma y′ en e⁻²ᵋy′. Por eso preserva la EDO pero cambia la condición y′(∞)=1. Las simetrías de una ecuación pueden dejar de ser simetrías del problema completo con condiciones de contorno.']
 ],formula(lines([text('y‴ + yy″ = 0'),text('⇓  r=y, v(r)=y′'),text('v vᵣᵣ + vᵣ² + r vᵣ = 0')]),'Reducción autónoma de Blasius'),
 more('Otra reducción y una práctica','<p>En x>0, s=ln x y R(s)=xy dan R‴+(R−6)R″+(11−3R)R′+2R²−6R=0. Esta forma es autónoma en s; después puedes tratar R′ como función de R para bajar el orden. La expresión se obtiene sustituyendo las derivadas, lo que evita depender de simplificaciones intermedias del PDF.</p><p>Práctica: en el sistema numérico q′=−yq, q(0)>0 implica q(x)=q(0)e^{−∫y dx}>0 mientras exista la solución. Por tanto y′ crece. Compruébalo en el gráfico y explica por qué una curva que descendiera indicaría un error.</p>')),
 note('En un sistema, todas las variables dependientes y el tiempo pueden transformarse. Cada ecuación aporta una condición de Lie; no basta con conservar una de ellas.',[
 ['Escribe el operador sobre soluciones','Para ẋ=f(t,x,y), ẏ=g(t,x,y), Γ=τ∂t+ξ∂x+η∂y y Dₜ=∂t+f∂x+g∂y. Las condiciones son Dₜξ−fDₜτ=τfₜ+ξfₓ+ηfᵧ y Dₜη−gDₜτ=τgₜ+ξgₓ+ηgᵧ.'],
 ['Reconoce el ejemplo cuadrático','ẋ=2xy, ẏ=x²+y² admite ∂t y Γ=t∂t−x∂x−y∂y. Su flujo es t̄=eᵋt, x̄=e⁻ᵋx, ȳ=e⁻ᵋy. Las velocidades y los términos cuadráticos cambian con el mismo factor e⁻²ᵋ.'],
 ['Reduce con las coordenadas del libro','En x≠0, r=y/x, u=tx y v=−ln|x| satisfacen Γr=Γu=0 y Γv=1. Quedan du/dr=−(1+2ru)/(r²−1) y dv/dr=2r/(r²−1). Se integran como u=(−r+C₁)/(r²−1), v=ln|r²−1|+C₂.'],
 ['Comprueba con un desacoplamiento','Pon U=x+y, V=y−x. Directamente U̇=U² y V̇=V². Así U=U₀/(1−U₀t), V=V₀/(1−V₀t), x=(U−V)/2 y y=(U+V)/2. Esta solución exacta alimenta el laboratorio y ofrece una comprobación independiente.'],
 ['Recupera las familias excluidas','La reducción r,u,v divide por x y r²−1. Hay que recuperar x=0 y las diagonales y=±x: en ellas una de U,V se anula. La solución desacoplada las incluye automáticamente. No atravieses los polos t=1/U₀ o 1/V₀ desde t=0.']
 ],formula(text('Γ = t∂ₜ−x∂ₓ−y∂ᵧ')+mo(',')+text('U̇=U², V̇=V²'),'Generador de escala del sistema y variables desacopladas'),
 more('Ejercicio resuelto: la diagonal y=x','<p>Si y₀=x₀=a, U₀=2a y V₀=0. Entonces x=y=a/(1−2at). Su derivada es 2a²/(1−2at)²=2xy=x²+y². Se trata de una solución válida que el cambio r=y/x deja en r=1 constante.</p><p>En el ansatz τ=τ(t), ξ=ξ(x), η=η(y), el capítulo obtiene τ=a₁t+a₀, ξ=−a₁x, η=−a₁y. La hipótesis del ansatz debe permanecer visible: reduce el cálculo, pero no autoriza una afirmación general sobre todos los sistemas.</p>')),
 note('El sistema ẍ=x/(x²+y²)², ÿ=y/(x²+y²)² describe una fuerza radial hacia fuera, proporcional a 1/u³. Su simetría de rotación permite separar la evolución del radio y del ángulo.',[
 ['Elige la orientación angular','Usamos Γ=−y∂x+x∂y, r=t, u=√(x²+y²), v=atan2(y,x). Entonces Γu=0, Γv=1. El libro usa el generador opuesto en la p. 71, que daría Γv=−1 con esa elección de ángulo; cambiar su signo resuelve la orientación. El ángulo requiere una carta local.'],
 ['Transforma las aceleraciones','En polares, la componente radial es u″−uv′² y la angular 2u′v′+uv″. La fuerza tiene componentes 1/u³ y 0. Por tanto u″=uv′²+1/u³ y v″=−2u′v′/u.'],
 ['Integra el momento angular','La ecuación angular equivale a (u²v′)′=0. L=u²v′ es constante. Al sustituir, u″=(L²+1)/u³. La rotación suma ε a v y conserva u,L y la evolución radial.'],
 ['Integra la energía radial','Multiplica por u′: E=½u′²+(L²+1)/(2u²) es constante. Con u(0)=u₀ y u′(0)=w₀, A=2E=w₀²+(L²+1)/u₀², y u²=At²+2u₀w₀t+u₀². Es siempre positivo: no hay colisión con el origen para estos datos reales.'],
 ['Reconstruye la órbita','Integra v′=L/u² para encontrar el ángulo y luego x=u cos v, y=u sin v. El laboratorio usa esta solución exacta, rota la trayectoria completa y comprueba numéricamente L y E. L=0 produce movimiento radial, aunque la fuerza siga siendo no nula.']
 ],formula(lines([text('L = u²v′'),text('u″')+mo('=')+frac(sup('L','2')+mo('+')+mn('1'),sup('u','3')),mi('E')+mo('=')+frac(text('u′²'),mn('2'))+mo('+')+frac(sup('L','2')+mo('+')+mn('1'),mn('2')+sup('u','2'))]),'Momento angular, ecuación radial y energía'),
 more('Las cuatro simetrías y el cierre del capítulo','<p>El cálculo con τ=T(t) produce τ=k₂t²+2k₁t+k₀, ξ=(k₂t+k₁)x+k₃y, η=−k₃x+(k₂t+k₁)y. Sus cuatro parámetros corresponden a traslación temporal, escala, transformación proyectiva del tiempo y rotación. Para una escala finita, t̄=e^{2ε}t y (x̄,ȳ)=eᵋ(x,y); la aceleración y la fuerza pesan −3.</p><p>La recurrencia de prolongación se aplica a cada variable dependiente: ξ⁽ᵏ⁾=Dₜξ⁽ᵏ⁻¹⁾−x⁽ᵏ⁾Dₜτ, y análogamente para η. Los acoplamientos de un sistema importan al resolver las ecuaciones determinantes; no extrapoles el resultado de esta fuerza a cualquier fuerza radial.</p><p>Práctica final: para un sistema autónomo de tres variables con términos cuadráticos, prueba el generador t∂t−Σxᵢ∂xᵢ. Comprueba sus pesos en cada término y detecta cómo un término lineal rompería esa escala. Este razonamiento prepara el ejercicio de tres ecuaciones que cierra el capítulo.</p>'))
];
const Q=(q,a,correct,why)=>({q:inlineMath(q),a:a.map(inlineMath),correct,why:inlineMath(why)});
export const arrigo2Quizzes=[
 [Q('¿Dónde se evalúa el campo al reconstruir un flujo?',['En el punto que está evolucionando','Siempre en el punto inicial','Solo al final'],0,'Las ecuaciones del flujo son dx̄/dε=ξ(x̄,ȳ), dȳ/dε=η(x̄,ȳ). Congelar el campo solo da la aproximación tangente.'),Q('Para Γ=∂x+2x∂y, ¿qué combinación permanece fija?',['y+x²','y−x²','x−y'],1,'Γ(y−x²)=2x−2x=0. El flujo incluye ε² y conserva esa diferencia exactamente.'),Q('¿Qué impide construir Γs=1?',['Un punto donde Γ=0','Que Γ dependa de x','Una simetría continua'],0,'Un campo nulo deriva cualquier función a cero. Se necesitan cartas donde el campo y el cambio de coordenadas sean regulares.'),Q('En r=xy, s=ln x para la Riccati inicial, ¿qué soluciones revisas antes de invertir dr/dx?',['y=±1/x','Todas las constantes y','Solo y=0'],0,'dr/dx=(r²−1)/x se anula en r=±1. Las curvas y=±1/x satisfacen la EDO y no se representan como s(r).')],
 [Q('¿Cuál es la prolongación de primer orden?',['ηₓ+ηᵧp','ηₓ+(ηᵧ−ξₓ)p−ξᵧp²','ξₓ+ηᵧ'],1,'La variable independiente también cambia. La regla de la cadena aporta −ξₓp y −ξᵧp².'),Q('En y′=xy³, ξ=ax, η=by, ¿qué pesos sirven?',['b=a','b=0 para todo a','b=−a'],2,'El residuo de Lie es −2(a+b)xy³. La identidad exige a+b=0, no solo que se anule en un punto.'),Q('Un residuo cero en (1,0) demuestra…',['La simetría global','Una comprobación puntual','Que el ansatz es completo'],1,'Una identidad debe valer en un dominio abierto. En y=0 muchos residuos se anulan accidentalmente.'),Q('¿Qué implica un ansatz ξ=A(x), η=B(x)y?',['Encuentra toda simetría posible','Restringe la búsqueda a esa forma','Evita verificar Lie'],1,'El ansatz facilita las ecuaciones determinantes, pero puede excluir otros generadores. Hay que comprobar las familias obtenidas.')],
 [Q('Para y′+Py=Q, ¿qué coordenada elimina y de la EDO?',['s=μy, μ=e^{∫P dx}','s=y/μ','s=y²'],0,'(μy)′=μQ cuando μ′=Pμ. La ecuación reducida es una cuadratura.'),Q('¿Qué añade el flujo lineal a y?',['ε siempre','ε/μ(x)','εμ(x)'],1,'El generador vertical es η=1/μ. En coordenadas s, el incremento sí es la constante ε.'),Q('En y=x−1+Ce⁻ˣ, ¿qué hace ε?',['C pasa a C+ε','C pasa a Ceᵋ','C no cambia'],0,'s=eˣy=eˣ(x−1)+C. El flujo s̄=s+ε desplaza la constante aditivamente.'),Q('¿Se conserva y(0)=2 bajo cualquier ε?',['Sí, por ser simetría','Solo si ε=0 en esta familia','Solo si x>0'],1,'La simetría conserva la EDO, pero ȳ(0)=2+ε cambia la condición inicial fija.')],
 [Q('¿Qué sustitución linealiza Bernoulli?',['z=yⁿ','z=y^{1−n}','z=ln x'],1,'Multiplicar por (1−n)y⁻ⁿ da z′+(1−n)Pz=(1−n)Q en una rama donde la potencia está definida.'),Q('Para el ejemplo cúbico, ¿cuánto vale ds/dx?',['−1/(4x)','1/x','x²'],1,'La derivada de −1/(2x²y²), tras sustituir y′=−y/x+xy³, es 1/x. El PDF contiene una errata.'),Q('¿Qué solución se pierde al usar y⁻²?',['y=0','y=1','Toda solución positiva'],0,'La EDO original admite y=0. La coordenada s diverge allí, de modo que se recupera por sustitución directa.'),Q('¿Puede el flujo local cruzar 1−2εx²y²=0?',['Sí si cambia el signo','No, alcanza un polo','Sí con ε negativo'],1,'La rama real conectada con la identidad exige ese denominador positivo. Al llegar a cero la solución se hace infinita.')],
 [Q('¿Qué conserva la dilatación común?',['xy','y/x','x+y'],1,'Los factores eᵋ se cancelan en y/x. Esa razón es la coordenada invariante.'),Q('Antes de invertir dr/ds=F(r)−r, ¿qué guardas?',['Las raíces de F(r)−r','Las raíces de x','Solo r=0'],0,'Cada raíz r₀ produce la solución y=r₀x. Dividir por F(r)−r eliminaría esas rectas.'),Q('Para el ejemplo con raíz, ¿qué ocurre si x<0?',['Nada cambia','√(x²+y²)/x cambia de signo respecto a la carta x>0','La EDO no existe en ningún x<0'],1,'√(x²+y²)=|x|√(1+r²); el cociente |x|/x distingue las dos cartas.'),Q('En F(r)=r+r²−1, ¿qué rectas son soluciones?',['y=±x','y=±2x','Solo y=0'],0,'Los equilibrios del campo reducido son r²−1=0. Sustituir y=±x confirma las dos soluciones.')],
 [Q('¿Qué condición local corresponde a exactitud?',['Mₓ=Nᵧ','Mᵧ=Nₓ','M=N'],1,'Si M=Φₓ y N=Φᵧ, las derivadas mixtas coinciden. En un dominio local regular permite construir una primitiva.'),Q('¿Cuándo puedes usar μ=1/(Mξ+Nη)?',['Cuando Γ es simetría y la contracción no se anula','Para cualquier campo Γ','Incluso en cualquier polo'],0,'La fórmula se apoya en la simetría y en la transversalidad del campo respecto a la ecuación diferencial.'),Q('I=y(2x⁴−y³)/x² es…',['Invariante del grupo ponderado','Integral primera que escala como e^{10ε}','Una constante para todo punto del plano'],1,'Es constante a lo largo de cada solución, pero ΓI=10I. El grupo transforma una curva I=K en otra con K escalado.'),Q('¿Por qué revisar y=0 aparte?',['La EDO no la admite','El factor integrante es singular allí','Porque μ debe ser único'],1,'La forma original sí admite y=0. El factor μ divide por y y no representa esa solución regular en x≠0.')],
 [Q('¿Qué dato necesita la reducción clásica de Riccati?',['Una solución particular y₁','Dos simetrías de rotación','Un coeficiente constante P'],0,'Al restar y₁ desaparece el término independiente. Encontrar esa solución puede ser la parte difícil del problema.'),Q('Si q′=Aq+Pq² y w=1/q, ¿qué resulta?',['w′+Aw=−P','w′−Aw=P','w′=q²'],0,'w′=−q′/q²=−Aw−P. Es una EDO lineal para w.'),Q('¿Qué solución queda fuera de w=1/(y−y₁)?',['y=y₁','y=−y₁ siempre','Todas las no constantes'],0,'El denominador se anula justamente en la particular conocida, que debe añadirse de nuevo a la familia.'),Q('En el ejemplo, ¿qué coordenada se traslada?',['s=−e⁴ˣ/(y−eˣ)','s=y−eˣ','s=e⁻ˣy'],0,'Con H=e⁻⁴ˣ, s=−1/[H(y−y₁)] satisface Γs=1 y s′=e³ˣ.')],
 [Q('¿Qué es Dₓ en el espacio de jets?',['Solo ∂x','∂x+p∂y+q∂p+⋯','La derivada de ε'],1,'La derivada total sigue una curva y sus derivadas; las coordenadas dependientes también varían.'),Q('Para ξ=ax, η=by, ¿qué peso tiene y″?',['b','b−a','b−2a'],2,'Cada derivación respecto a x resta un peso a. La prolongación segunda tiene coeficiente (b−2a)y″.'),Q('Para Γ=y∂x, ¿cuál es η⁽²⁾?',['−3pq','−p²','q'],0,'η⁽¹⁾=−p²; Dₓη⁽¹⁾−qDₓξ=−2pq−pq=−3pq.'),Q('En Δ=y″−F(x,y,p), ¿qué sustituyes tras prolongar?',['p=F','y″=F','y=F'],1,'La restricción debe corresponder al orden de la ecuación: q=F. p sigue siendo una coordenada independiente del jet.')],
 [Q('¿Qué transformación preserva y″=0?',['ȳ=y+εx','ȳ=y+εx²','ȳ=y+εx³'],0,'La segunda derivada de εx es cero. Los otros incrementos introducen curvatura.'),Q('Reducir de segundo a primer orden garantiza…',['Una solución elemental','Una EDO de orden menor, no su integración elemental','Que no existan soluciones especiales'],1,'La simetría reduce el orden. La nueva ecuación puede seguir siendo no lineal y difícil de integrar.'),Q('Si y=u′/u, ¿a qué equivale y″+3yy′+y³=0?',['u″=0','u‴=0 donde u≠0','u′=u³'],1,'Derivando el cociente, la combinación no lineal es u‴/u. Por ello un polinomio cuadrático produce soluciones.'),Q('¿Por qué y=1/(x+c) queda fuera de s(r) para Γ₁?',['No resuelve la EDO','r=x−1/y es constante','s es siempre cero'],1,'En esa solución r=−c. La inversión para usar r como variable independiente falla aunque la curva sea solución.')],
 [Q('¿Cuál es la reducción autónoma correcta de Blasius?',['v vᵣᵣ+vᵣ²+r vᵣ=0','vᵣᵣ+r=0','v′=−v³'],0,'Con r=y y v=y′, y″=v vᵣ y y‴=v(vᵣ²+v vᵣᵣ). Divide por v solo donde v≠0.'),Q('¿Se puede usar y como variable independiente en la pared y′(0)=0?',['Sí sin restricciones','No en ese punto','Solo si y(0)=0'],1,'El cambio requiere y′≠0. El sistema original permite integrar desde la pared sin esa división.'),Q('El botón de disparo impone…',['y′(8)≈1 numéricamente','y′(∞)=1 exactamente','y″=0 en todo x'],0,'Se resuelve un problema truncado por bisección. El extremo 8 aproxima la condición lejana; se comprueba su estabilidad numérica.'),Q('La escala de Blasius conserva también y′(∞)=1 para todo ε…',['Sí','No, y′ cambia por e⁻²ᵋ','Solo cambia y″'],1,'Una simetría de la EDO puede romper sus condiciones de contorno. La normalización de la velocidad selecciona una escala.')],
 [Q('En el sistema cuadrático, ¿qué transformación temporal acompaña x̄=e⁻ᵋx?',['t̄=eᵋt','t̄=t+ε siempre','t̄=e⁻ᵋt'],0,'La derivada d x̄/d t̄ pesa −2, igual que 2x̄ȳ. Sin transformar el tiempo los pesos no coinciden.'),Q('Para U=x+y, V=y−x, ¿qué sistema queda?',['U̇=V², V̇=U²','U̇=U², V̇=V²','U̇=V̇=0'],1,'Sumando y restando las ecuaciones originales aparecen (x+y)² y (y−x)². El sistema se desacopla.'),Q('¿Qué solución exige revisión al dividir por r²−1?',['y=x','Toda órbita con y=0','Solo el origen'],0,'La diagonal y=x tiene r=1 constante; también y=−x tiene r=−1. El desacoplamiento las conserva.'),Q('Si U₀>0, ¿qué limita la evolución conectada a t=0?',['t=1/U₀','t=U₀','No hay límite'],0,'U=U₀/(1−U₀t) alcanza un polo en 1/U₀. Una expresión al otro lado no prolonga la solución a través de infinito.')],
 [Q('¿Qué cantidad constante proviene de la ecuación angular?',['L=u²v′','L=uv','L=u′v′'],0,'La ecuación u v″+2u′v′=0 equivale a (u²v′)′=0. Ese L es el momento angular por unidad de masa.'),Q('Con el signo de fuerza del libro, la ecuación radial es…',['u″=−(L²+1)/u³','u″=(L²+1)/u³','u″=0'],1,'La fuerza apunta hacia fuera. La contribución centrífuga y la fuerza suman L²/u³+1/u³.'),Q('¿Qué cambia al rotar toda la órbita?',['El ángulo inicial','La energía radial','El radio en cada instante'],0,'La rotación suma una constante al ángulo y conserva u, sus derivadas, L y E.'),Q('¿Qué significa L=0?',['La fuerza desaparece','El movimiento es radial','La partícula debe estar en el origen'],1,'v′=L/u²=0 fija la dirección angular. La aceleración radial sigue siendo 1/u³; el origen está excluido.')]
];
