import {fmt,colors,range,note,frame,sampled,plot,bindRanges,directionField} from './arrigo.mjs';
import * as M from './arrigo2-math.mjs';
import {inlineMath} from './arrigo2-content.mjs';
const mathNote=(title,s)=>note(title,inlineMath(s));
const $=s=>document.querySelector(s),v=id=>Number($('#'+id).value);
const select=(id,label,options)=>`<div class="field"><label for="${id}">${label}</label><select id="${id}">${options.map(([k,s])=>`<option value="${k}">${s}</option>`).join('')}</select></div>`;
const result='<div id="a2-result" class="result-box" aria-live="polite"></div>';
const pair=(title,controls)=>`<div class="card a2-controls"><h3>${inlineMath(title)}</h3><div class="reduction-controls">${inlineMath(controls)}</div>${result}</div><div class="two-col reduction-plots"><div class="viz"><div class="viz-header"><span id="a2-title-left">ECUACIÓN ORIGINAL</span></div><div id="a2-left"></div></div><div class="viz"><div class="viz-header"><span id="a2-title-right">COORDENADAS CANÓNICAS</span></div><div id="a2-right"></div></div></div><div class="a2-legend"><span>● Violeta: original</span><span>● Verde: transformado</span></div>`;
const status=(label,s)=>`<span class="mini-label">${label}</span><div class="result-equation">${inlineMath(s)}</div>`;
function bind(ids,selects,update){bindRanges(ids,update);selects.forEach(id=>$('#'+id).onchange=update);update();}
function infinitesimals(root){
 root.innerHTML=frame('DEL CAMPO AL MOVIMIENTO','',`<h3>Exacto y aproximación tangente</h3>${select('a2-model','Generador',[['parabola','∂x+2x∂y · parábola'],['dilation','x∂x−y∂y · escala opuesta'],['rotation','−y∂x+x∂y · rotación'],['reciprocal','x²∂x+y²∂y · recíprocos']])}${range('a2-e','Parámetro ε',-.8,.8,.01,.5)}<button id="a2-half" class="primary-button">Reducir ε a la mitad</button>${result}`)+mathNote('Reto: mide el error al dividir ε por dos.','La aproximación P+εΓ(P) descarta términos de orden ε². El punto naranja es esa aproximación; la curva verde es el recorrido exacto. En la rotación, el ángulo canónico se interpreta localmente.');
 const update=()=>{const k=$('#a2-model').value,e=v('a2-e'),P=[1,.6],G=M.generator(k,...P),T=M.flow(k,...P,e),A=P.map((x,i)=>x+e*G[i]),rs=M.canonical(k,...P),rt=M.canonical(k,...T);let paths=[{data:sampled(t=>M.flow(k,...P,t),-.9,.9),color:colors.ghost},{data:sampled(t=>M.flow(k,...P,t),0,e),color:colors.changed,width:4}],segments=[];
  for(let x=-2;x<=2;x+=.5)for(let y=-2;y<=2;y+=.5){const g=M.generator(k,x,y),n=Math.hypot(...g);if(n)segments.push({a:[x,y],b:[x+.14*g[0]/n,y+.14*g[1]/n]});}
  $('#lie-chart').innerHTML=plot({title:'Flujo exacto, aproximación de primer orden y campo generador',bounds:[-3,Math.max(3,T[0]*1.15),-2,Math.max(2.5,T[1]*1.15)],equal:k==='rotation',paths,segments,points:[{xy:P,color:colors.original,label:'P'},{xy:T,label:'exacto'},{xy:A,color:colors.red,label:'tangente'}]});
  $('#a2-result').innerHTML=status('DISTANCIA ENTRE EXACTO Y TANGENTE',fmt(Math.hypot(T[0]-A[0],T[1]-A[1]),5))+`<p>r(P)=${fmt(rs[0])}; r(TεP)=${fmt(rt[0])}</p><p>s(TεP)−s(P)=${fmt(rt[1]-rs[1])} = ε</p><p class="helper">${{parabola:'r=y−x², s=x',dilation:'r=xy, s=ln|x|',rotation:'r=x²+y², s=atan2(y,x)',reciprocal:'r=1/x−1/y, s=−1/y'}[k]}. Γr=0, Γs=1 en esta carta.</p>`;
 };bind(['a2-e'],['a2-model'],update);$('#a2-half').onclick=()=>{$('#a2-e').step='any';$('#a2-e').value=v('a2-e')/2;$('#a2-e').dispatchEvent(new Event('input'));};
}
function determining(root){
 root.innerHTML=frame('UNA IDENTIDAD, DOS PESOS','',`<h3>Busca una simetría de y′=xy³</h3><p class="helper">Prueba Γ=ax∂x+by∂y. El gráfico compara las tangentes bajo su flujo.</p>${range('a2-a','Peso a de x',-2,2,.05,1)}${range('a2-b','Peso b de y',-2,2,.05,1)}${range('a2-e','Parámetro finito ε',-.5,.5,.01,.25)}<button id="a2-solve" class="primary-button">Imponer b = −a</button>${result}`)+mathNote('Reto: separa prueba simbólica y comprobación puntual.','El residuo es −2(a+b)xy³. La identidad exige a+b=0. Un cero en x=0 o y=0 no basta. En los apuntes encontrarás cómo un ansatz de funciones A(x), B(x) genera ecuaciones determinantes.');
 const update=()=>{const a=v('a2-a'),b=v('a2-b'),e=v('a2-e'),P=[1,.65],p=P[0]*P[1]**3,T=[Math.exp(a*e)*P[0],Math.exp(b*e)*P[1]],pt=Math.exp((b-a)*e)*p,ft=T[0]*T[1]**3,bounds=[0,2.6,0,2.2],segments=directionField((x,y)=>x*y**3,bounds),tangent=(P,m,color)=>{const d=.2/Math.hypot(1,m);return {a:[P[0]-d,P[1]-d*m],b:[P[0]+d,P[1]+d*m],color,width:4};};segments.push(tangent(P,p,colors.original),tangent(T,pt,colors.changed));$('#lie-chart').innerHTML=plot({title:'Campo de pendientes y tangentes transformadas para pesos de escala',bounds,segments,points:[{xy:P,color:colors.original,label:'P'},{xy:T,label:'TεP'}]});$('#a2-result').innerHTML=status('RESIDUO SIMBÓLICO',`R = ${fmt(-2*(a+b),2)} xy³`)+`<p class="${Math.abs(a+b)<1e-10?'pass':'fail'}">${Math.abs(a+b)<1e-10?'Identidad R=0: estos pesos son una simetría.':'El residuo no es una identidad nula.'}</p><p>Pendiente transportada: ${fmt(pt,5)}<br>Campo en TεP: ${fmt(ft,5)}<br>Diferencia finita: ${fmt(pt-ft,5)}</p>`;};bind(['a2-a','a2-b','a2-e'],[],update);$('#a2-solve').onclick=()=>{$('#a2-b').value=-v('a2-a');$('#a2-b').dispatchEvent(new Event('input'));};
}
function linear(root){
 root.innerHTML=pair('De y′+λy=x a s′=xe^{λx}',`<div>${range('a2-l','Coeficiente λ de la EDO',.4,2,.02,1)}${range('a2-C','Constante C',-.5,3,.02,1)}</div><div>${range('a2-e','Flujo ε',-1,1,.02,.5)}<p class="helper">r=x, s=e^{λx}y. Mantén λ fijo para comparar soluciones de una misma ecuación.</p></div>`)+mathNote('Reto: compara la separación entre curvas.','En y vale εe^{−λx}; en s vale exactamente ε. Al crecer x, las curvas originales se acercan aunque las transformadas mantengan una separación vertical constante.');
 const update=()=>{const l=v('a2-l'),C=v('a2-C'),e=v('a2-e'),p=sampled(x=>[x,M.linear(x,C,l)],0,3),q=sampled(x=>[x,M.linear(x,C+e,l)],0,3),s=(x,c)=>Math.exp(l*x)*(x/l-1/l**2)+c;$('#a2-left').innerHTML=plot({title:'Soluciones lineales antes y después del flujo',bounds:[0,3,Math.min(...[...p,...q].map(z=>z[1]))-.5,Math.max(...[...p,...q].map(z=>z[1]))+.5],paths:[{data:p},{data:q,color:colors.changed,dash:true}]});const data=sampled(x=>[x,s(x,C)],0,2),data2=sampled(x=>[x,s(x,C+e)],0,2),all=[...data,...data2].map(p=>p[1]);$('#a2-right').innerHTML=plot({title:'Coordenada s y su traslación vertical constante',bounds:[0,2,Math.min(...all)-1,Math.max(...all)+1],labels:['r','s'],paths:[{data},{data:data2,color:colors.changed,dash:true}]});$('#a2-result').innerHTML=status('LA CONSTANTE SE DESPLAZA',`C̄ = C+ε = ${fmt(C+e)}`)+`<p>ȳ−y en x=2: ${fmt(e*Math.exp(-2*l),5)} · s̄−s=${fmt(e)}.</p>`;};bind(['a2-l','a2-C','a2-e'],[],update);
}
function bernoulli(root){
 root.innerHTML=pair('Una potencia, dos ramas y una solución aparte',`<div>${select('a2-branch','Rama',[['1','y positiva'],['-1','y negativa'],['0','Solución y=0']])}${range('a2-C','Constante C',-3,-1,.02,-2)}</div><div>${range('a2-e','Traslación ε de s',-.6,.6,.02,.3)}<p class="helper">s=−1/(2x²y²), s′=1/x. La línea s=0 marca el límite de la rama real.</p></div>`)+mathNote('Reto: recupera la solución que la potencia inversa oculta.','Selecciona y=0. Sigue siendo solución, pero su coordenada s no existe. Cambia ε y observa que los polos de las ramas no se pueden cruzar.');
 const update=()=>{const C=v('a2-C'),e=v('a2-e'),sign=v('a2-branch');$('#a2-left').innerHTML=plot({title:'Bernoulli, ramas reales antes y después del flujo',bounds:[.25,4,-4,4],paths:[{data:sampled(x=>[x,M.bernoulli(x,C,sign)],.25,4)},{data:sampled(x=>[x,M.bernoulli(x,C+e,sign)],.25,4),color:colors.changed,dash:true}]});$('#a2-right').innerHTML=plot({title:'Bernoulli en coordenadas canónicas; parte admisible s menor que cero',bounds:[.25,4,-5,1],labels:['r','s'],paths:sign===0?[]:[{data:sampled(x=>[x,Math.log(x)+C],.25,Math.min(4,Math.exp(-C)))},{data:sampled(x=>[x,Math.log(x)+C+e],.25,Math.min(4,Math.exp(-C-e))),color:colors.changed,dash:true}],segments:[{a:[.25,0],b:[4,0],color:colors.red}]});$('#a2-result').innerHTML=sign===0?status('SOLUCIÓN RECUPERADA','y=0 · s no está definida'):status('LÍMITE DE LA RAMA TRANSFORMADA',`0 &lt; x &lt; e^{−(C+ε)} = ${fmt(Math.exp(-C-e))}`)+`<p>s̄=ln x+${fmt(C+e)}. La parte de la fórmula con s̄≥0 no representa una y real.</p>`;};bind(['a2-C','a2-e'],['a2-branch'],update);
}
function homogeneous(root){
 root.innerHTML=pair('La escala desaparece de r=y/x',`<div>${select('a2-model','Ecuación o solución',[['book','Libro: F(r)=r+√(1+r²)'],['roots','F(r)=r+r²−1 · rama r>1'],['plus','Solución recuperada r=1'],['minus','Solución recuperada r=−1']])}${range('a2-C','Constante C',-.7,.7,.02,0)}</div><div>${range('a2-e','Dilatación ε',-.7,.7,.02,.3)}<p class="helper">x̄=eᵋx, ȳ=eᵋy. En la carta x>0, s=ln x pasa a s+ε.</p></div>`)+mathNote('Reto: busca los equilibrios antes de dividir.','En el modelo F(r)=r+r²−1, las rectas r=±1 resuelven la EDO pero no son gráficas s(r). El laboratorio las muestra sin asignarles una inversa inexistente.');
 const update=()=>{const k=$('#a2-model').value,C=v('a2-C'),e=v('a2-e'),special=['plus','minus'].includes(k),r0=k==='plus'?1:-1,s=r=>k==='book'?Math.asinh(r)+C:.5*Math.log((r-1)/(r+1))+C,domain=k==='book'?[-2,2]:[1.015,4],data=special?sampled(x=>[x,r0*x],.1,4):sampled(r=>[Math.exp(s(r)),r*Math.exp(s(r))],...domain),trans=data.map(([x,y])=>[Math.exp(e)*x,Math.exp(e)*y]);$('#a2-left').innerHTML=plot({title:'Curva homogénea y su dilatación común',bounds:[0,5,-5,5],paths:[{data},{data:trans,color:colors.changed,dash:true}]});$('#a2-right').innerHTML=plot({title:'Reducción homogénea; traslación de s o recta r constante',bounds:k==='book'?[-2,2,-3,3]:[-1.5,4.2,-3,2],labels:['r','s'],paths:special?[{data:sampled(t=>[r0,t],-3,2),color:colors.original},{data:sampled(t=>[r0,t],-3,2),color:colors.changed,dash:true}]:[{data:sampled(r=>[r,s(r)],...domain)},{data:sampled(r=>[r,s(r)+e],...domain),color:colors.changed,dash:true}]});$('#a2-result').innerHTML=special?status('EQUILIBRIO DEL CAMPO REDUCIDO',`r=${r0} · dr/ds=0`)+`<p>La dilatación recorre la misma recta. No puedes invertir r(s) en esta solución.</p>`:status('REDUCCIÓN',k==='book'?'ds/dr=1/√(1+r²)':'ds/dr=1/(r²−1)')+`<p>C̄=${fmt(C+e)}. ${k==='roots'?'Se muestra la rama r>1; los apuntes explican las otras ramas.':'El modelo con raíz está en la carta x>0.'}</p>`;};bind(['a2-C','a2-e'],['a2-model'],update);
}
function exact(root){
 root.innerHTML=frame('CURVAS IMPLÍCITAS Y ESCALA PONDERADA','',`<h3>Integral primera y simetría</h3><p class="helper">M dx+N dy=0, Γ=3x∂x+4y∂y. El gráfico traza I(x,y)=K sin despejar y.</p>${range('a2-K','Nivel inicial K',.3,4,.02,1.2)}${range('a2-e','Parámetro ε',-.08,.08,.002,.04)}${result}`)+mathNote('Reto: explica por qué K cambia.','I es constante al seguir una curva solución, pero no al seguir el flujo de Γ. La escala lleva I=K a I=e^{10ε}K. El potencial Φ=(1/10)ln|I| sí se traslada exactamente en ε.')+`<div class="card"><h3>Un factor integrante con excepciones</h3><p>μ=1/[5xy(2x⁴−y³)]. Donde existe, (μM)ᵧ=(μN)ₓ. Las soluciones y=0 y y=∛2 · x<sup>4/3</sup> quedan fuera de μ y se recuperan directamente en x>0.</p></div>`;
 const update=()=>{const K=v('a2-K'),e=v('a2-e'),Kb=K*Math.exp(10*e),bounds=[.35,2.2,.05,3],segments=[...M.contours(M.exactIntegral,K,bounds).map(s=>({...s,color:colors.original,width:2.5})),...M.contours(M.exactIntegral,Kb,bounds).map(s=>({...s,color:colors.changed,width:2.5}))];$('#lie-chart').innerHTML=plot({title:'Niveles implícitos de la integral primera antes y después de la escala',bounds,segments});$('#a2-result').innerHTML=status('EL GRUPO CAMBIA EL NIVEL',`K̄ = e^{10ε}K = ${fmt(Kb)}`)+`<p>Φ̄−Φ = 0,1 ln(K̄/K) = ${fmt(Math.log(Kb/K)/10,4)}</p><p class="helper">La curva verde satisface también la misma EDO. Se muestran niveles positivos en x,y>0; el factor no está definido en I=0.</p>`;};bind(['a2-K','a2-e'],[],update);
}
function riccati(root){
 root.innerHTML=pair('Una particular conocida convierte Riccati en lineal',`<div>${select('a2-branch','Familia',[['general','Familia general mostrada'],['particular','Solución particular y₁=eˣ']])}${range('a2-C','Constante C',1,4,.02,2)}</div><div>${range('a2-e','Flujo ε',-.5,.5,.02,.3)}<p class="helper">s=−e⁴ˣ/(y−eˣ), s′=e³ˣ. El flujo traslada C sin cambiar la EDO.</p></div>`)+mathNote('Reto: separa la particular de la familia transformada.','Cuando y=y₁, el recíproco no está definido. La simetría fija esa curva porque su generador vertical H(y−y₁)² se anula sobre ella.');
 const update=()=>{const C=v('a2-C'),e=v('a2-e'),special=$('#a2-branch').value==='particular',f=x=>special?Math.exp(x):M.riccati2(x,C);$('#a2-left').innerHTML=plot({title:'Soluciones de Riccati y particular conocida',bounds:[-1,1,-7,4],paths:[{data:sampled(x=>[x,f(x)],-1,1)},{data:sampled(x=>[x,special?Math.exp(x):M.riccati2(x,C+e)],-1,1),color:colors.changed,dash:true},{data:sampled(x=>[x,Math.exp(x)],-1,1),color:colors.ghost,dash:true}]});$('#a2-right').innerHTML=plot({title:'Riccati reducida a una cuadratura en s',bounds:[-1,1,0,12],labels:['r','s'],paths:special?[]:[{data:sampled(x=>[x,Math.exp(3*x)/3+C],-1,1)},{data:sampled(x=>[x,Math.exp(3*x)/3+C+e],-1,1),color:colors.changed,dash:true}]});$('#a2-result').innerHTML=special?status('SOLUCIÓN RECUPERADA','y₁=eˣ · s no existe'):status('ECUACIÓN LINEAL PARA w',`w′+4w=−e⁻ˣ`)+`<p>C̄=${fmt(C+e)}. La curva gris es y₁=eˣ. Los polos para otras constantes se analizan en los apuntes.</p>`;};bind(['a2-C','a2-e'],['a2-branch'],update);
}
function prolongation(root){
 root.innerHTML=frame('LA MISMA CURVA EN EL ESPACIO DE JETS','',`<h3>Transforma las derivadas</h3>${select('a2-model','Movimiento',[['scale','Escala: ax∂x+by∂y'],['shear','Cizalla: y∂x']])}${range('a2-a','Peso a',-1.5,1.5,.05,1)}${range('a2-b','Peso b',-2,2,.05,-1)}${range('a2-e','Parámetro ε',-.4,.4,.01,.2)}${result}`)+`<div class="card"><h3>Del punto al jet</h3><div id="a2-jets" class="table-scroll"></div><p class="helper">La curva de referencia es y=0,5+0,7x−0,2x²+0,1x³. Su jet en x=0 es (y,p,q,z)=(0,5; 0,7; −0,4; 0,6). Las derivadas de la cizalla se evalúan en el punto transformado.</p></div>`+mathNote('Reto: cuenta cuánto cambia cada derivada.','Una derivada resta un peso de la variable independiente. Para una cizalla, aparecen productos p², pq y q²: no basta con copiar el coeficiente de y.');
 const update=()=>{const a=v('a2-a'),b=v('a2-b'),e=v('a2-e'),k=$('#a2-model').value,jets=[.5,.7,-.4,.6],next=k==='scale'?M.scalingJets(jets,a,b,e):[.5,...M.shearJets(...jets.slice(1),e)],coef=k==='scale'?jets.map((t,i)=>(b-i*a)*t):[0,-(.7**2),-3*.7*(-.4),-4*.7*.6-3*.4**2],fn=x=>.5+.7*x-.2*x*x+.1*x**3,data=sampled(x=>[x,fn(x)],-1.4,1.4),trans=data.map(([x,y])=>k==='scale'?[Math.exp(a*e)*x,Math.exp(b*e)*y]:[x+e*y,y]);$('#lie-chart').innerHTML=plot({title:'Polinomio local original y curva transformada por escala o cizalla',bounds:[-2.5,2.5,-2,3],paths:[{data},{data:trans,color:colors.changed,dash:true}],points:[{xy:[0,.5],color:colors.original,label:'jet'},{xy:k==='scale'?[0,Math.exp(b*e)*.5]:[e*.5,.5],label:'jet transformado'}]});$('#a2-jets').innerHTML=`<table><caption>Coeficientes infinitesimales y valores finitos</caption><thead><tr><th scope="col">Coordenada</th><th scope="col">Original</th><th scope="col">Velocidad en ε=0</th><th scope="col">Transformada</th></tr></thead><tbody>${['y','p=y′','q=y″','z=y‴'].map((s,i)=>`<tr><th scope="row">${s}</th><td>${fmt(jets[i])}</td><td>${fmt(coef[i])}</td><td>${fmt(next[i])}</td></tr>`).join('')}</tbody></table>`;$('#a2-result').innerHTML=status('REGLA DE PROLONGACIÓN','η⁽ᵏ⁾=Dₓη⁽ᵏ⁻¹⁾−y⁽ᵏ⁾Dₓξ')+`<p>${k==='scale'?'Peso de y‴: b−3a = '+fmt(b-3*a):'Cizalla: η⁽³⁾=−4pz−3q². En el punto, 1+εp='+fmt(1+e*.7)+'.'}</p>`;['a2-a','a2-b'].forEach(id=>$('#'+id).closest('.field').hidden=k==='shear');};bind(['a2-a','a2-b','a2-e'],['a2-model'],update);
}
function second(root){
 root.innerHTML=pair('Tres ecuaciones: compara el efecto de la simetría',`<div>${select('a2-model','Ejemplo',[['nonlinear','y″+3yy′+y³=0 · a s″=1'],['free','y″=0 · transformación válida'],['wrong','y″=0 · contraejemplo cuadrático'],['scaling','y″+yy′+xy⁴=0 · escala']])}${range('a2-B','Coeficiente b de la solución',.6,2,.02,1)}</div><div>${range('a2-e','Parámetro ε',-.15,.3,.01,.15)}<p class="helper">En el ejemplo no lineal se usa u=x²+bx+2, y=u′/u. El flujo de Γ₁ traslada s y mantiene r.</p></div>`)+mathNote('Reto: no confundas reducir con resolver.','La ecuación con escala baja a una EDO de primer orden no lineal. La otra se vuelve s″=1. Las curvas singulares de una carta se recuperan en los apuntes.');
 const update=()=>{const k=$('#a2-model').value,B=v('a2-B'),e=v('a2-e');let data,trans,canonical1=[],canonical2=[],leftBounds=[0,4,0,2],rightBounds=[-2.5,2,-.5,5],info;$('#a2-title-right').textContent='COORDENADAS CANÓNICAS';
  if(k==='nonlinear'){data=sampled(x=>[x,M.nonlinearSecond(x,1,B,2)],0,4);trans=data.map(([x,y])=>M.secondFlow(x,y,e));canonical1=data.map(([x,y])=>[x-1/y,1/(2*y*y)]);canonical2=trans.map(([x,y])=>[x-1/y,1/(2*y*y)]);info='r=x−1/y permanece fijo; s=1/(2y²) se traslada. d²s/dr²=1.';}
  else if(k==='scaling'){data=M.rk4((x,[y,p])=>[p,-y*p-x*y**4],[.5,.1],1,2.5,.006).map(([x,y])=>[x,y]);trans=data.map(([x,y])=>M.flow('dilation',x,y,e));canonical1=data.map(([x,y])=>[x*y,Math.log(x)]);canonical2=trans.map(([x,y])=>[x*y,Math.log(x)]);leftBounds=[.7,3.5,-1,1];rightBounds=[-.5,2,-.5,1.5];info='Todos los términos de y″+yy′+xy⁴ pesan −3. Reducida: p′=(r⁴−r²+2r)p³+(r−3)p².';}
  else {data=sampled(x=>[x,.5+B*x],0,3);trans=data.map(([x,y])=>[x,y+e*(k==='wrong'?x*x:x)]);canonical1=sampled(x=>[x,0],0,3);canonical2=sampled(x=>[x,k==='wrong'?2*e:0],0,3);leftBounds=[0,3,0,9];rightBounds=[0,3,-.5,.7];$('#a2-title-right').textContent='SEGUNDA DERIVADA';info=k==='wrong'?`ȳ″=2ε=${fmt(2*e)}: el movimiento cuadrático no preserva y″=0 salvo ε=0.`:'Sumar εx cambia la pendiente de la recta y mantiene y″=0.';}
  $('#a2-left').innerHTML=plot({title:'Soluciones de segundo orden originales y transformadas',bounds:leftBounds,paths:[{data},{data:trans,color:colors.changed,dash:true}]});$('#a2-right').innerHTML=plot({title:k==='free'||k==='wrong'?'Segunda derivada antes y después del movimiento':'Curvas de segundo orden en coordenadas canónicas',bounds:rightBounds,labels:k==='free'||k==='wrong'?['x','y″']:['r','s'],paths:[{data:canonical1},{data:canonical2,color:colors.changed,dash:true}]});$('#a2-result').innerHTML=status('COMPROBACIÓN',k==='nonlinear'?'s̄=s+ε':k==='scaling'?'r̄=r, s̄=s+ε':'Curvatura de la imagen')+`<p>${info}</p>`;$('#a2-B').closest('.field').hidden=k==='scaling';};bind(['a2-B','a2-e'],['a2-model'],update);
}
function blasius(root){
 root.innerHTML=frame('PERFIL Y DISPARO NUMÉRICO','',`<h3>y‴+yy″=0</h3><p class="helper">Integra desde y(0)=y′(0)=0. Ajusta la curvatura inicial a=y″(0) hasta que y′ en el extremo se acerque a 1.</p>${range('a2-a','Curvatura inicial a',.15,.8,.001,.47)}${select('a2-end','Extremo del intervalo',[['6','x=6'],['8','x=8'],['10','x=10']])}<button id="a2-shoot" class="primary-button">Ajustar y′ en el extremo a 1</button>${result}`)+`<div class="reduction-flow card"><div><span class="mini-label">TERCER ORDEN</span><p>y‴+yy″=0</p></div><div><span class="mini-label">AUTONOMÍA</span><p>r=y, v(r)=y′</p></div><div><span class="mini-label">SEGUNDO ORDEN</span><p>v vᵣᵣ+vᵣ²+r vᵣ=0</p></div></div>`+mathNote('Reto: cambia el extremo y repite el ajuste.','La condición lejana se aproxima en un intervalo finito. La reducción en r=y no es válida en la pared donde y′=0; por eso integramos el sistema original. El modelo usa Runge–Kutta de orden 4, con paso máximo 0,015.');
 const update=()=>{const a=v('a2-a'),end=v('a2-end'),rows=M.blasius(a,end),last=rows.at(-1);$('#lie-chart').innerHTML=plot({title:'Blasius: velocidad y prima, curvatura y segunda y referencia uno',bounds:[0,end,0,1.5],paths:[{data:rows.map(r=>[r[0],r[2]])},{data:rows.map(r=>[r[0],r[3]]),color:colors.changed}],segments:[{a:[0,1],b:[end,1],color:colors.red}],labels:['x','y′, y″']});$('.plot-legend').innerHTML='<span><i style="background:#c3b6ff"></i>y′ · velocidad</span><span><i style="background:#6ce2bc"></i>y″ · curvatura</span><span><i style="background:#ffac95"></i>Objetivo 1</span>';$('#a2-result').innerHTML=status('VELOCIDAD EN EL EXTREMO',`y′(${end})=${fmt(last[2],6)}`)+`<p>Error respecto a 1: ${fmt(last[2]-1,6)}<br>y(${end})=${fmt(last[1])}; y″(${end})=${fmt(last[3],6)}</p><p class="helper" id="a2-shot-message">El ajuste numérico resuelve la condición en x=${end}; cambia el extremo para comprobar estabilidad.</p>`;};bind(['a2-a'],['a2-end'],update);$('#a2-shoot').onclick=()=>{const a=M.shootBlasius(v('a2-end'));$('#a2-a').value=a;$('#a2-a-value').textContent=fmt(a,6); // Preserve full precision despite the slider step.
  $('#a2-a').step='any';$('#a2-a').value=a;update();$('#a2-shot-message').textContent='Bisección completada: a='+fmt(a,7)+'. La condición se ha ajustado en el extremo seleccionado.';};
}
function systems(root){
 root.innerHTML=pair('ẋ=2xy, ẏ=x²+y²: tiempo y fase',`<div>${range('a2-x','Dato inicial x₀',-.8,.8,.02,.4)}${range('a2-y','Dato inicial y₀',-.4,.4,.02,.1)}</div><div>${range('a2-e','Escala ε',-.5,.5,.02,.3)}${range('a2-t','Punto sobre el recorrido (fracción)',0,1,.01,.5)}</div>`)+mathNote('Reto: selecciona x₀=0 o y₀=±x₀.','La solución desacoplada U=x+y, V=y−x incluye las familias que el cambio r=y/x excluye. La escala transforma el tiempo: comparar x̄(t̄) con x(t) en el mismo valor numérico de tiempo ocultaría ese cambio.');
 const update=()=>{const x=v('a2-x'),y=v('a2-y'),e=v('a2-e'),T=Math.min(1.5,.82/Math.max(x+y,y-x,.01)),t=T*v('a2-t'),P=M.coupled(t,x,y),factor=Math.exp(-e),rows=sampled(t=>[t,...M.coupled(t,x,y)],0,T);$('#a2-title-left').textContent='PLANO DE FASE (x,y)';$('#a2-title-right').textContent='VARIABLE x FRENTE AL TIEMPO';$('#a2-left').innerHTML=plot({title:'Sistema cuadrático: órbita de fase y órbita escalada',bounds:[-3,3,-2,4],paths:[{data:rows.map(r=>r.slice(1))},{data:rows.map(r=>r.slice(1).map(z=>z*factor)),color:colors.changed,dash:true}],points:[{xy:P,color:colors.original,label:'t'},{xy:P.map(z=>z*factor),label:'t̄'}]});$('#a2-right').innerHTML=plot({title:'Variable x antes y después de escalar tanto el tiempo como la amplitud',bounds:[0,Math.max(T,T*Math.exp(e)),-3,3],labels:['t','x(t)'],paths:[{data:rows.map(r=>[r[0],r[1]])},{data:rows.map(r=>[Math.exp(e)*r[0],factor*r[1]]),color:colors.changed,dash:true}],points:[{xy:[t,P[0]],color:colors.original,label:'t'},{xy:[Math.exp(e)*t,factor*P[0]],label:'t̄'}]});$('#a2-result').innerHTML=status('ESCALA DEL TIEMPO',`t=${fmt(t)} → t̄=${fmt(Math.exp(e)*t)}`)+`<p>(x,y)=(${fmt(P[0])}; ${fmt(P[1])})<br>(x̄,ȳ)=(${fmt(factor*P[0])}; ${fmt(factor*P[1])})</p><p>${Math.abs(P[0])<1e-9?'x=0: r=y/x no existe, pero la solución sí.':`r=y/x=${fmt(P[1]/P[0])}; ū=t̄x̄=tx=${fmt(t*P[0])}.`}</p><p class="helper">El intervalo termina antes del primer polo. Solución exacta en U,V; los gráficos se recortan al rango visible.</p>`;};bind(['a2-x','a2-y','a2-e','a2-t'],[],update);
}
function central(root){
 root.innerHTML=pair('De la órbita a una ecuación radial',`<div>${range('a2-L','Momento angular L',-2,2,.02,1)}${range('a2-w','Velocidad radial inicial u′₀',-.5,.5,.02,-.2)}</div><div>${range('a2-e','Rotación ε (radianes)',-3.14,3.14,.02,.6)}${range('a2-t','Instante t',-3,3,.02,.5)}</div>`)+mathNote('Reto: cambia el signo de L y después haz L=0.','L cambia el sentido del recorrido angular; L=0 da una trayectoria radial. Rotar la órbita cambia su orientación y conserva el radio en cada instante, el momento angular y la energía. El radio inicial vale 1,2.');
 const update=()=>{const L=v('a2-L'),w=v('a2-w'),e=v('a2-e'),t=v('a2-t'),f=t=>M.central(t,L,1.2,w),P=f(t),Q=M.central(t,L,1.2,w,e),data=sampled(t=>{const p=f(t);return [p.x,p.y];},-3,3),trans=data.map(([x,y])=>M.flow('rotation',x,y,e)),rad=sampled(t=>[t,f(t).u],-3,3),extent=Math.max(2,...[...data,...trans].map(p=>Math.max(Math.abs(p[0]),Math.abs(p[1]))))+.4;$('#a2-title-left').textContent='ÓRBITA EN EL PLANO';$('#a2-title-right').textContent='RADIO FRENTE AL TIEMPO';$('#a2-left').innerHTML=plot({title:'Órbita bajo fuerza central repulsiva y rotación de la trayectoria',bounds:[-extent,extent,-extent,extent],equal:true,paths:[{data},{data:trans,color:colors.changed}],points:[{xy:[0,0],color:colors.ghost,label:'O · u=0'},{xy:[P.x,P.y],color:colors.original,label:'P'},{xy:[Q.x,Q.y],label:'P̄'}]});$('#a2-right').innerHTML=plot({title:'Radio de la órbita: original y rotado coinciden',bounds:[-3,3,0,Math.max(...rad.map(p=>p[1]))+.4],labels:['t','u'],paths:[{data:rad},{data:rad,color:colors.changed,dash:true}],points:[{xy:[t,P.u],label:'u=ū'}]});$('#a2-result').innerHTML=status('CANTIDADES CONSERVADAS',`L=${fmt(P.u**2*P.omega)} · E=${fmt(.5*P.w**2+(L*L+1)/(2*P.u**2))}`)+`<p>u=${fmt(P.u)}, ū=${fmt(Q.u)}<br>v̄−v=${fmt(Q.theta-P.theta)} = ε<br>u″=(L²+1)/u³=${fmt((L*L+1)/P.u**3)}</p><p class="helper">La fuerza es radial hacia fuera: el signo positivo importa. Trayectoria calculada mediante la solución exacta.</p>`;};bind(['a2-L','a2-w','a2-e','a2-t'],[],update);
}
export function renderArrigo2(section,root){[infinitesimals,determining,linear,bernoulli,homogeneous,exact,riccati,prolongation,second,blasius,systems,central][section-1](root);}
