import {E,I,TAU,H,V,B,apply,mul,transpose,det,near,rotation,rz,reflection,power,matrixOrder,classes,orbit,pole,pointGroup,operation,solids,edges,latticeMatrix,integerMatrix,unit} from './symmetry.mjs';
const $=s=>document.querySelector(s);
const palette=['#6ce2bc','#ffac95','#b9a7ff','#ffe6a1','#89caff'];
const fmt=n=>Math.abs(n)<.00001?'0':n.toLocaleString('es',{maximumFractionDigits:3});
const subs=n=>String(n).replace(/\d/g,d=>'₀₁₂₃₄₅₆₇₈₉'[d]);
const supers=n=>String(n).replace(/\d/g,d=>'⁰¹²³⁴⁵⁶⁷⁸⁹'[d]);
const name=(family,n)=>({C:'C',D:'D',Ch:'C',Cv:'C',S:'S',Dh:'D',Dd:'D'}[family]||family)+(['C','D','Ch','Cv','S','Dh','Dd'].includes(family)?subs(n):'')+({Ch:'h',Cv:'v',Dh:'h',Dd:'d'}[family]||'');
const option=(values,current)=>values.map(([v,t])=>'<option value="'+v+'" '+(String(v)===String(current)?'selected':'')+'>'+t+'</option>').join('');
const field=(id,label,values,current)=>'<div class="field"><label for="'+id+'">'+label+'</label><select id="'+id+'">'+option(values,current)+'</select></div>';
const range=(id,label,min,max,value,step=1)=>'<div class="field"><label for="'+id+'">'+label+' <output id="'+id+'-label">'+value+'°</output></label><input class="range" type="range" id="'+id+'" min="'+min+'" max="'+max+'" step="'+step+'" value="'+value+'"></div>';
const insight=(symbol,title,text)=>'<div class="insight"><span class="insight-symbol">'+symbol+'</span><p><strong>'+title+'</strong>'+text+'</p></div>';
const matrix=m=>'<div class="numeric-matrix" aria-label="Matriz de la operación">'+m.map(x=>'<span>'+fmt(x)+'</span>').join('')+'</div>';
const vector=v=>'('+v.map(fmt).join('; ')+')';
const ns=Array.from({length:5},(_,i)=>[i+2,'n = '+(i+2)]);
let host;
const state={elements:{type:'C',n:3,theta:50,phi:23,k:1},conj:{n:3,x:'B'},rot:{family:'D',n:3,k:1},lattice:{kind:'square',n:4,h:1,k:1,l:1},poly:{solid:'tetra',k:1},cyclic:{family:'Ch',n:3,k:1},dihedral:{family:'Dh',n:3,k:1},full:{family:'Td',k:1},catalog:{system:'all',id:'C3v'},color:{n:4,k:1,flip:1,a:1,b:1}};
const camera={yaw:-.65,pitch:.45};
function project(v,scale=108){const m=mul(rotation([1,0,0],camera.pitch),rz(camera.yaw)),p=apply(m,v);return[200+scale*p[0],168-scale*p[2],p[1]];}
const xy=p=>p[0].toFixed(2)+','+p[1].toFixed(2);
function segment(a,b,color='#4e5b7b',dash=false,width=1.3){const p=project(a),q=project(b);return'<path d="M'+xy(p)+'L'+xy(q)+'" fill="none" stroke="'+color+'" stroke-width="'+width+'" '+(dash?'stroke-dasharray="4 5"':'')+'/>';}
function spaceSVG(points,{selected=null,vertices=null,links=[],colors=false,axis=null,plane=null,title='Direcciones sobre una esfera'}={}){
 let s='<svg class="space-svg" viewBox="0 0 400 340" role="img" aria-label="'+title+'"><title>'+title+'</title>';
 if(!vertices){for(const plane of [0,1,2]){const pts=Array.from({length:61},(_,i)=>{const a=i*TAU/60;return plane===0?[Math.cos(a),Math.sin(a),0]:plane===1?[Math.cos(a),0,Math.sin(a)]:[0,Math.cos(a),Math.sin(a)];});s+='<polyline points="'+pts.map(p=>xy(project(p))).join(' ')+'" fill="none" stroke="#394562" stroke-width="1"/>';}}
 if(plane){const corners=plane==='H'?[[-1,-1,0],[1,-1,0],[1,1,0],[-1,1,0]]:[[-1,0,-1],[1,0,-1],[1,0,1],[-1,0,1]];s+='<polygon points="'+corners.map(p=>xy(project(p))).join(' ')+'" fill="#b9a7ff20" stroke="#b9a7ff" stroke-width="1.2"/>';}
 for(let i=0;i<3;i++){const a=[0,0,0];a[i]=1.3;s+=segment(a,a.map(x=>-x),'#53607d',true);const p=project(a);s+='<text x="'+p[0]+'" y="'+p[1]+'" fill="#aab4d0" font-size="14">'+['x','y','z'][i]+'</text>';}
 if(vertices)for(const[a,b]of links)s+=segment(vertices[a],vertices[b],'#8896b6',false,1.5);
 if(axis){const a=unit(axis).map(x=>x*1.35);s+=segment(a,a.map(x=>-x),'#ffe6a1',false,2.5);}
 const nodes=points.map((p,i)=>({p:project(p),i})).sort((a,b)=>a.p[2]-b.p[2]);
 for(const{p,i}of nodes)s+='<circle cx="'+p[0]+'" cy="'+p[1]+'" r="'+(vertices?6:5)+'" fill="'+(colors?palette[i%palette.length]:(points[i][2]>=0?'#6ce2bc':'#ffac95'))+'" stroke="#131a33" stroke-width="1"/>';
 if(selected){const p=project(selected);s+='<circle cx="'+p[0]+'" cy="'+p[1]+'" r="10" fill="none" stroke="#fff" stroke-width="2"/>';}
 return s+'</svg>';
}
function poleSVG(points,selected=null){let s='<svg class="pole-svg" viewBox="0 0 340 340" role="img" aria-label="Proyección estereográfica: círculo arriba, cruz abajo"><title>Figura de polos; círculos en el hemisferio superior, cruces en el inferior</title><circle cx="170" cy="170" r="126" fill="none" stroke="#9ca8c5" stroke-width="1.5"/><path d="M30 170H310M170 30V310" stroke="#394562" stroke-dasharray="4 5"/><text x="308" y="163" fill="#aab4d0" font-size="13">x</text><text x="177" y="32" fill="#aab4d0" font-size="13">y</text>';
 for(const p of points){const[u,v,sign]=pole(p),x=170+126*u,y=170-126*v;s+=sign>0?'<circle cx="'+x+'" cy="'+y+'" r="5.5" fill="none" stroke="#6ce2bc" stroke-width="2"/>':'<path d="M'+(x-4)+','+(y-4)+'l8 8m0 -8l-8 8" stroke="#ffac95" stroke-width="2"/>';}
 if(selected){const[u,v]=pole(selected);s+='<circle cx="'+(170+126*u)+'" cy="'+(170-126*v)+'" r="10" fill="none" stroke="white" stroke-width="1.5"/>';}
 return s+'</svg>';
}
function visual(title,tag){return'<div class="viz"><div class="viz-header"><span>'+title+'</span><span class="viz-tag">'+tag+'</span></div><div class="dual-viz"><div id="space-plot"></div><div id="pole-plot"></div></div><div class="viz-bottom"><span>○ arriba · × abajo · anillo blanco: imagen elegida</span></div><div class="camera-control">'+range('camera','Vista',-90,90,Math.round(camera.yaw*180/Math.PI))+'</div></div>';}
function bindCamera(draw){$('#camera').oninput=()=>{camera.yaw=Number($('#camera').value)*Math.PI/180;$('#camera-label').textContent=$('#camera').value+'°';draw();};}
function stats(group){const own=group.filter(m=>det(m)>0).length,cls=classes(group);return'<div class="stat-row"><div><strong>'+group.length+'</strong><span>elementos</span></div><div><strong>'+own+'</strong><span>propios</span></div><div><strong>'+cls.length+'</strong><span>clases</span></div></div><p class="helper">Tamaños de clases: '+cls.map(c=>c.length).sort((a,b)=>a-b).join(' + ')+'.</p>';}
function membership(group,m){return group.some(g=>near(g,m));}
function selectElement(group,k){return field('element','Operación espacial',group.map((m,i)=>[i,(i===0?'E':('g'+i))+' · '+operation(m)]),k);}
const generic=unit([.37,.61,.79]);
function groupView(s,title,description,families,footer){
 const group=pointGroup(s.family,s.n||3);if(s.k>=group.length)s.k=0;
 host.innerHTML='<div class="lab">'+visual(title,name(s.family,s.n))+'<div class="control-panel"><h3>'+description+'</h3>'+field('family','Familia',families,s.family)+(s.n?field('n',s.family==='S'?'Índice n del generador Sₙ':'Orden del eje principal',ns,s.n):'')+selectElement(group,s.k)+'<div id="group-result" aria-live="polite"></div></div></div>'+footer;
 const draw=()=>{const m=group[s.k],p=apply(m,generic),pts=orbit(group,generic);$('#space-plot').innerHTML=spaceSVG(pts,{selected:p});$('#pole-plot').innerHTML=poleSVG(pts,p);$('#group-result').innerHTML=stats(group)+'<div class="result-box"><span class="mini-label">OPERACIÓN SELECCIONADA</span><div class="result-equation">det g = '+(det(m)>0?'+1':'−1')+'</div><p>'+operation(m)+'.</p><p>Inversión en el grupo: <strong>'+(membership(group,I)?'sí':'no')+'</strong>. Espejo σₕ: <strong>'+(membership(group,H)?'sí':'no')+'</strong>.</p></div><details class="compact-details"><summary>Ver matriz y coordenadas</summary>'+matrix(m)+'<p class="helper">g·P = '+vector(p)+'</p></details>';};
 $('#family').onchange=()=>{s.family=$('#family').value;s.k=1;groupView(s,title,description,families,footer);$('#family').focus();};
 if(s.n)$('#n').onchange=()=>{s.n=Number($('#n').value);s.k=1;groupView(s,title,description,families,footer);$('#n').focus();};
 $('#element').onchange=()=>{s.k=Number($('#element').value);draw();};bindCamera(draw);draw();
}
function renderElements(){const s=state.elements;
 host.innerHTML='<div class="lab">'+visual('DEL ESPACIO AL PAPEL','PROYECCIÓN ESTEREOGRÁFICA')+'<div class="control-panel"><h3>Sigue un punto</h3>'+field('type','Operación',[['C','Cₙ · rotación'],['H','σₕ · espejo horizontal'],['V','σᵥ · espejo vertical'],['I','I · inversión'],['S','Sₙ · rotación-reflexión']],s.type)+field('n','Orden del giro',ns,s.n)+range('theta','Ángulo desde z',10,170,s.theta)+range('phi','Azimut',0,360,s.phi)+field('repeat','Número de aplicaciones',Array.from({length:13},(_,i)=>[i,i]),s.k)+'<div id="element-result" aria-live="polite"></div></div></div>'+insight('○','Una dirección se convierte en un polo.','La esfera muestra la órbita completa del punto. Cambia el número de aplicaciones para seguir una imagen concreta en ambas vistas. Un círculo y una cruz pueden coincidir en el plano sin representar el mismo punto del espacio.')+'<details class="extension"><summary>Dos espejos producen un giro</summary><div class="detail-body">'+range('mirror-angle','Ángulo entre planos',0,90,30)+'<div id="mirror-result" aria-live="polite"></div></div></details>';
 function draw(){const r=rz(TAU/s.n),m={C:r,H,V,I,S:mul(r,H)}[s.type],order=matrixOrder(m),p=[Math.sin(s.theta*Math.PI/180)*Math.cos(s.phi*Math.PI/180),Math.sin(s.theta*Math.PI/180)*Math.sin(s.phi*Math.PI/180),Math.cos(s.theta*Math.PI/180)],pts=Array.from({length:order},(_,i)=>apply(power(m,i),p)),q=apply(power(m,s.k),p);$('#space-plot').innerHTML=spaceSVG(pts,{selected:q,axis:s.type==='C'||s.type==='S'?[0,0,1]:null,plane:s.type==='H'||s.type==='S'?'H':s.type==='V'?'V':null});$('#pole-plot').innerHTML=poleSVG(pts,q);$('#element-result').innerHTML='<div class="result-box"><span class="mini-label">APLICACIONES: '+s.k+'</span><div class="result-equation">Orden = '+order+'</div><p>det = '+(det(m)>0?'+1':'−1')+' · '+(det(m)>0?'propia':'impropia')+'.</p><p>P′ = '+vector(q)+'</p></div><p class="helper">'+(s.type==='S'?'Sₙ aquí es una rotación-reflexión; no es el grupo de permutaciones del capítulo 1.':'E = identidad · I = inversión espacial.')+'</p>';$('#n').disabled=!['C','S'].includes(s.type);}
 for(const id of ['type','n','repeat'])$('#'+id).onchange=()=>{s[id==='repeat'?'k':id]=id==='type'?$('#'+id).value:Number($('#'+id).value);draw();};
 for(const id of ['theta','phi'])$('#'+id).oninput=()=>{s[id]=Number($('#'+id).value);$('#'+id+'-label').textContent=s[id]+'°';draw();};
 $('#mirror-angle').oninput=mirrorDraw;
 function mirrorDraw(){const a=Number($('#mirror-angle').value);$('#mirror-angle-label').textContent=a+'°';const A=reflection([-Math.sin(a*Math.PI/180),Math.cos(a*Math.PI/180),0]),M=mul(A,V);$('#mirror-result').innerHTML='<div class="result-box"><div class="result-equation">σ(φ) σ(0) = C('+2*a+'°)</div><p>Primero el plano de 0°, después el de '+a+'°. El orden inverso da −'+2*a+'°. '+(near(M,mul(V,A))?'En este caso los productos coinciden.':'En este caso no conmutan.')+'</p></div>'+matrix(M);}
 bindCamera(draw);draw();mirrorDraw();
}
function renderConjugation(){const s=state.conj;host.innerHTML='<div class="lab">'+visual('CONJUGAR UNA ROTACIÓN','x Cₙ x⁻¹')+'<div class="control-panel"><h3>¿Se invierte el giro?</h3>'+field('n','Rotación alrededor de z',[[3,'C₃ · 120°'],[4,'C₄ · 90°'],[6,'C₆ · 60°']],s.n)+field('conjugator','Operación x',[['B','b · giro 180° alrededor de x'],['H','σₕ · reflexión horizontal'],['V','σᵥ · reflexión vertical']],s.x)+'<div id="conjugate-result" aria-live="polite"></div><p class="helper">Verde: P. Coral: CₙP. Lavanda: xCₙx⁻¹P.</p></div></div>'+insight('↔','Cambiar z por −z no basta.','La reflexión horizontal conmuta con el giro. La reflexión vertical y el giro transversal invierten Cₙ. El determinante explica por qué estas operaciones se comportan de forma distinta.');
 const draw=()=>{const r=rz(TAU/s.n),x={B,H,V}[s.x],c=mul(mul(x,r),transpose(x)),same=near(c,r),pts=[generic,apply(r,generic),apply(c,generic)];$('#space-plot').innerHTML=spaceSVG(pts,{colors:true,selected:pts[2],axis:apply(x,[0,0,1])});$('#pole-plot').innerHTML=poleSVG(pts,pts[2]);$('#conjugate-result').innerHTML='<div class="result-box"><div class="result-equation">x C'+subs(s.n)+' x⁻¹ = C'+subs(s.n)+(same?'':'⁻¹')+'</div><p>'+(same?'Conserva la rotación.':'Invierte el sentido de la rotación.')+'</p><p>det x = '+(det(x)>0?'+1':'−1')+'<br>x·z = '+vector(apply(x,[0,0,1]))+'</p></div><details class="compact-details"><summary>Resultado matricial</summary>'+matrix(c)+'</details>';};
 $('#n').onchange=()=>{s.n=Number($('#n').value);draw();};$('#conjugator').onchange=()=>{s.x=$('#conjugator').value;draw();};bindCamera(draw);draw();}
function renderRotations(){groupView(state.rot,'SOLO ROTACIONES','Genera las imágenes de P',[['C','Cₙ · un eje'],['D','Dₙ · ejes transversales']],insight('+1','En Dₙ todas las operaciones son rotaciones 3D.','rⁿ=b²=E y brb⁻¹=r⁻¹. Prueba D₂: sus cuatro elementos conmutan. D₃ tiene la misma estructura abstracta que las seis simetrías planas del capítulo 1.'));}
function latticeSVG(kind,n){const angle=TAU/n,c=Math.cos(angle),s=Math.sin(angle),t=Math.sqrt(3)/2,points=[];for(let i=-5;i<=5;i++)for(let j=-5;j<=5;j++){const p=kind==='square'?[i,j]:[i+j/2,j*t];if(Math.hypot(...p)<4.5)points.push(p);}const screen=p=>[200+p[0]*32,170-p[1]*32],p1=p=>[c*p[0]-s*p[1],s*p[0]+c*p[1]];let svg='<svg class="space-svg" viewBox="0 0 400 340" role="img" aria-label="Red original en blanco y red girada en verde o coral"><title>Comparación de la red original con su giro de '+Math.round(360/n)+' grados</title><path d="M30 170H370M200 15V325" stroke="#394562"/>';for(const p of points){const[x,y]=screen(p);svg+='<circle cx="'+x+'" cy="'+y+'" r="4" fill="#c0c9df"/>';}for(const p of points){const[x,y]=screen(p1(p));svg+='<circle cx="'+x+'" cy="'+y+'" r="6" fill="none" stroke="'+(integerMatrix(latticeMatrix(kind,n))?'#6ce2bc':'#ffac95')+'" stroke-width="1.5"/>';}return svg+'</svg>';}
function planePolygon(h,k,l){const coeff=[h,k,l],verts=solids.cube.vertices.map(p=>p.map(x=>(x+1)/2)),es=edges(verts),points=[];for(const[a,b]of es){const p=verts[a],q=verts[b],u=coeff.reduce((s,c,i)=>s+c*p[i],0),v=coeff.reduce((s,c,i)=>s+c*q[i],0);if(Math.abs(u-1)<1e-8)points.push(p);if((u-1)*(v-1)<0){const t=(1-u)/(v-u);points.push(p.map((x,i)=>x+t*(q[i]-x)));}if(Math.abs(v-1)<1e-8)points.push(q);}const unique=[...new Map(points.map(p=>[p.join(','),p])).values()];if(unique.length<3)return unique;const center=[0,1,2].map(i=>unique.reduce((s,p)=>s+p[i],0)/unique.length),normal=unit(coeff),ref=unit(unique[0].map((x,i)=>x-center[i])),side=[normal[1]*ref[2]-normal[2]*ref[1],normal[2]*ref[0]-normal[0]*ref[2],normal[0]*ref[1]-normal[1]*ref[0]];return unique.sort((a,b)=>{const angle=p=>Math.atan2(p.reduce((s,x,i)=>s+(x-center[i])*side[i],0),p.reduce((s,x,i)=>s+(x-center[i])*ref[i],0));return angle(a)-angle(b);});}
function renderLattice(){const s=state.lattice;host.innerHTML='<div class="lab"><div class="viz"><div class="viz-header"><span>¿EL GIRO CONSERVA LA RED?</span><span class="viz-tag">RED PERIÓDICA</span></div><div id="lattice-plot"></div><div class="viz-bottom"><span>Puntos blancos: red inicial · anillos: red girada</span></div></div><div class="control-panel"><h3>Prueba la periodicidad</h3>'+field('lattice','Red de referencia',[['square','Cuadrada'],['triangular','Triangular']],s.kind)+field('n','Orden n del giro',Array.from({length:8},(_,i)=>[i+1,'n = '+(i+1)+' · '+fmt(360/(i+1))+'°']),s.n)+'<div id="lattice-result" aria-live="polite"></div></div></div>'+insight('ℤ','La matriz debe tener entradas enteras en la base de la red.','La red cuadrada admite 90°; la triangular admite 60° y 120°. Un pentágono aislado puede tener simetría C₅ aunque una red periódica ordinaria no la admita.')+'<details class="extension"><summary>Índices de Miller: dibuja un plano (hkl)</summary><div class="detail-body"><p>Ejes ortogonales de longitud unidad. Un índice 0 significa paralelo a ese eje.</p><div class="miller-controls">'+['h','k','l'].map(id=>field('miller-'+id,id,[[0,0],[1,1],[2,2],[3,3]],s[id])).join('')+'</div><div class="two-col"><div class="viz" id="plane-plot"></div><div id="plane-result" aria-live="polite"></div></div></div></details>';
 const draw=()=>{const m=latticeMatrix(s.kind,s.n),ok=integerMatrix(m);$('#lattice-plot').innerHTML=latticeSVG(s.kind,s.n);$('#lattice-result').innerHTML='<div class="result-box"><div class="result-equation '+(ok?'pass':'fail')+'">'+(ok?'Conserva la red':'No conserva la red')+'</div><p>A⁻¹·Cₙ·A en la base elegida:</p><div class="numeric-matrix matrix-2">'+m.map(x=>'<span>'+fmt(x)+'</span>').join('')+'</div><p>Traza = '+fmt(m[0]+m[3])+'. '+(ok?'Las cuatro entradas son enteras.':'Alguna entrada no es entera.')+'</p></div>';};
 function planeDraw(){const coeff=[s.h,s.k,s.l];if(coeff.every(x=>x===0)){$('#plane-result').innerHTML='<p class="fail">(000) no define un plano: la ecuación sería 0=1. Elige al menos un índice no nulo.</p>';$('#plane-plot').innerHTML='';return;}const verts=solids.cube.vertices.map(p=>p.map(x=>(x+1)/2)),poly=planePolygon(...coeff),base=spaceSVG([],{vertices:verts,links:edges(verts),title:'Intersección del plano de Miller con la celda unidad'});$('#plane-plot').innerHTML=base.replace('</svg>','<polygon points="'+poly.map(p=>xy(project(p))).join(' ')+'" fill="#6ce2bc55" stroke="#6ce2bc" stroke-width="2"/></svg>');$('#plane-result').innerHTML='<div class="formula">'+s.h+'x + '+s.k+'y + '+s.l+'z = 1</div><p>Intersecciones: '+coeff.map((v,i)=>['x','y','z'][i]+': '+(v?fmt(1/v):'paralelo')).join(' · ')+'.</p><p class="helper">Se dibuja la parte del plano que atraviesa la celda, no un plano infinito. Coeficientes con factor común describen planos paralelos de la misma orientación; los índices de esa orientación se reducen.</p>';}
 $('#lattice').onchange=()=>{s.kind=$('#lattice').value;draw();};$('#n').onchange=()=>{s.n=Number($('#n').value);draw();};for(const id of ['h','k','l'])$('#miller-'+id).onchange=()=>{s[id]=Number($('#miller-'+id).value);planeDraw();};draw();planeDraw();}
function renderPolyhedra(){const s=state.poly,solid=solids[s.solid],group=pointGroup(solid.group),vertices=solid.vertices.map(unit),links=edges(vertices);if(s.k>=group.length)s.k=0;
 host.innerHTML='<div class="lab"><div class="viz"><div class="viz-header"><span>LOS CINCO SÓLIDOS REGULARES</span><span class="viz-tag">'+solid.group+' · '+group.length+' ROTACIONES</span></div><div id="poly-plot"></div><div class="viz-bottom"><span>El anillo blanco sigue el vértice 1.</span></div><div class="camera-control">'+range('camera','Vista',-90,90,Math.round(camera.yaw*180/Math.PI))+'</div></div><div class="control-panel"><h3>Una figura, muchos movimientos</h3>'+field('solid','Sólido regular',Object.entries(solids).map(([id,v])=>[id,v.name]),s.solid)+selectElement(group,s.k)+'<div id="poly-result" aria-live="polite"></div></div></div>'+insight('↔','Los sólidos duales comparten sus rotaciones.','Cubo y octaedro tienen O; dodecaedro e icosaedro tienen Y. Los colores siguen los vértices, aunque cada operación deje el sólido geométrico en la misma posición.');
 const draw=()=>{const pts=vertices.map(v=>apply(group[s.k],v));$('#poly-plot').innerHTML=spaceSVG(pts,{vertices,links,colors:true,selected:pts[0],title:solid.name+' con sus vértices transformados'});$('#poly-result').innerHTML='<div class="stat-row"><div><strong>'+solid.V+'</strong><span>vértices V</span></div><div><strong>'+solid.E+'</strong><span>aristas E</span></div><div><strong>'+solid.F+'</strong><span>caras F</span></div></div><div class="result-box"><div class="result-equation">'+solid.V+' − '+solid.E+' + '+solid.F+' = 2</div><p>p='+solid.p+' lados por cara · q='+solid.q+' caras por vértice.<br>1/p+1/q = '+fmt(1/solid.p+1/solid.q)+' &gt; 1/2.</p><p>'+group.length+' rotaciones · '+classes(group).length+' clases.<br>'+operation(group[s.k])+'.</p></div>';};
 $('#solid').onchange=()=>{s.solid=$('#solid').value;s.k=1;renderPolyhedra();$('#solid').focus();};$('#element').onchange=()=>{s.k=Number($('#element').value);draw();};bindCamera(draw);draw();}
function renderCyclic(){groupView(state.cyclic,'PROPIAS E IMPROPIAS','El espejo cambia el grupo',[['Ch','Cₙh · espejo horizontal'],['Cv','Cₙv · espejos verticales'],['S','⟨Sₙ⟩ · generador impropio']],insight('±','La mitad impropia forma una clase lateral del subgrupo propio.','Prueba C₃h frente a S₆: ambos tienen seis elementos, pero solo el primero contiene σₕ y solo el segundo contiene inversión. Cₙv tiene la misma estructura abstracta que Dₙ, con una realización espacial distinta.'));}
function ringPoints(n,diagonal){const twist=diagonal?Math.PI/n:0,start=-twist/2;return [1,-1].flatMap((z,j)=>Array.from({length:n},(_,i)=>{const a=i*TAU/n+start+j*twist;return[Math.cos(a),Math.sin(a),z*.63];}));}
function renderDihedral(){const s=state.dihedral,group=pointGroup(s.family,s.n),pts=ringPoints(s.n,s.family==='Dd'),links=[];for(let j=0;j<2;j++)for(let i=0;i<s.n;i++)links.push([j*s.n+i,j*s.n+(i+1)%s.n]);if(s.k>=group.length)s.k=0;host.innerHTML='<div class="lab"><div class="viz"><div class="viz-header"><span>DOS ANILLOS A ALTURAS OPUESTAS</span><span class="viz-tag">'+name(s.family,s.n)+'</span></div><div id="ring-plot"></div><div class="viz-bottom"><span>Modelo ideal · los colores siguen los vértices</span></div><div class="camera-control">'+range('camera','Vista',-90,90,Math.round(camera.yaw*180/Math.PI))+'</div></div><div class="control-panel"><h3>¿Alineados o intercalados?</h3>'+field('family','Planos añadidos',[['Dh','Dₙh · horizontal, anillos alineados'],['Dd','Dₙd · diagonal, anillos intercalados']],s.family)+field('n','Vértices de cada anillo',ns,s.n)+selectElement(group,s.k)+'<div id="ring-result" aria-live="polite"></div></div></div>'+insight('I','El mismo número de operaciones no garantiza la misma geometría.','Con n=3, D₃h tiene espejo horizontal y D₃d tiene inversión. Con n=4 sucede al revés para la inversión. D₄d existe como grupo geométrico, pero contiene S₈ y no es cristalográfico.');
 const draw=()=>{const image=pts.map(v=>apply(group[s.k],v)),matches=image.every(p=>pts.some(q=>near(p,q)));$('#ring-plot').innerHTML=spaceSVG(image,{vertices:pts,links,colors:true,selected:image[0],title:'Dos anillos con simetría '+name(s.family,s.n)});$('#ring-result').innerHTML=stats(group)+'<div class="result-box"><div class="result-equation">'+(membership(group,I)?'Contiene I':'No contiene I')+'</div><p>σₕ: '+(membership(group,H)?'sí':'no')+'. Operación: '+operation(group[s.k])+'.</p><p>'+(matches?'La operación conserva las posiciones del modelo.':'Las posiciones del modelo no coinciden.')+'</p></div>';};
 $('#family').onchange=()=>{s.family=$('#family').value;s.k=1;renderDihedral();$('#family').focus();};$('#n').onchange=()=>{s.n=Number($('#n').value);s.k=1;renderDihedral();$('#n').focus();};$('#element').onchange=()=>{s.k=Number($('#element').value);draw();};bindCamera(draw);draw();}
function renderFull(){groupView(state.full,'LOS GRUPOS POLIÉDRICOS','Compara los grupos completos',[['T','T · rotaciones, 12'],['Td','Td · tetraedro completo, 24'],['Th','Tₕ · T con inversión, 24'],['O','O · rotaciones, 24'],['Oh','Oₕ · cubo completo, 48'],['Y','Y · rotaciones, 60'],['Yh','Yₕ · icosaedro completo, 120']],insight('×2','Tₕ y Td requieren una comparación especial.','Td conserva un tetraedro; Tₕ contiene inversión y no conserva sus cuatro vértices. Aquí se dibuja la órbita de un punto genérico bajo el grupo elegido. Oₕ y Yₕ se obtienen añadiendo la inversión central.'));}
const crystalRows=[
 ['C1','C₁','1','Triclínico','C',1],['Ci','Cᵢ','1̅','Triclínico','Ci',1],
 ['C2','C₂','2','Monoclínico','C',2],['Cs','Cₛ','m','Monoclínico','Cs',1],['C2h','C₂h','2/m','Monoclínico','Ch',2],
 ['D2','D₂','222','Ortorrómbico','D',2],['C2v','C₂v','mm2','Ortorrómbico','Cv',2],['D2h','D₂h','mmm','Ortorrómbico','Dh',2],
 ['C4','C₄','4','Tetragonal','C',4],['S4','S₄','4̅','Tetragonal','S',4],['C4h','C₄h','4/m','Tetragonal','Ch',4],['D4','D₄','422','Tetragonal','D',4],['C4v','C₄v','4mm','Tetragonal','Cv',4],['D2d','D₂d','4̅2m','Tetragonal','Dd',2],['D4h','D₄h','4/mmm','Tetragonal','Dh',4],
 ['C3','C₃','3','Trigonal','C',3],['S6','S₆ / C₃i','3̅','Trigonal','S',6],['D3','D₃','32','Trigonal','D',3],['C3v','C₃v','3m','Trigonal','Cv',3],['D3d','D₃d','3̅m','Trigonal','Dd',3],
 ['C6','C₆','6','Hexagonal','C',6],['C3h','C₃h','6̅','Hexagonal','Ch',3],['C6h','C₆h','6/m','Hexagonal','Ch',6],['D6','D₆','622','Hexagonal','D',6],['C6v','C₆v','6mm','Hexagonal','Cv',6],['D3h','D₃h','6̅m2','Hexagonal','Dh',3],['D6h','D₆h','6/mmm','Hexagonal','Dh',6],
 ['T','T','23','Cúbico','T',3],['Th','Tₕ','m3̅','Cúbico','Th',3],['O','O','432','Cúbico','O',3],['Td','Td','4̅3m','Cúbico','Td',3],['Oh','Oₕ','m3̅m','Cúbico','Oh',3]
];
export {crystalRows};
function renderCatalog(){const s=state.catalog,rows=crystalRows.filter(r=>s.system==='all'||r[3]===s.system);if(!rows.some(r=>r[0]===s.id))s.id=rows[0][0];
 host.innerHTML='<div class="catalog-layout"><div class="card">'+field('system','Sistema cristalino',[['all','Todos · 32 grupos'],...['Triclínico','Monoclínico','Ortorrómbico','Tetragonal','Trigonal','Hexagonal','Cúbico'].map(v=>[v,v])],s.system)+'<div class="table-scroll"><table class="catalog-table"><caption>Selecciona un grupo para examinar sus operaciones.</caption><thead><tr><th>Schoenflies</th><th>Internacional</th><th>Orden</th></tr></thead><tbody>'+rows.map(r=>'<tr><td><button data-crystal="'+r[0]+'" class="'+(r[0]===s.id?'selected':'')+'" aria-pressed="'+(r[0]===s.id)+'">'+r[1]+'</button></td><td class="math">'+r[2]+'</td><td>'+pointGroup(r[4],r[5]).length+'</td></tr>').join('')+'</tbody></table></div><p class="helper">'+rows.length+' grupos en esta vista.</p></div><div><div class="card" id="catalog-detail" aria-live="polite"></div><div class="viz"><div class="viz-header"><span>ÓRBITA EN FIGURA DE POLOS</span></div><div id="catalog-poles"></div></div></div></div>'+insight('m','La barra internacional indica giro seguido de inversión.','3̅ corresponde al grupo S₆; 6̅ corresponde a C₃h. La operación Sₙ del libro combina giro y reflexión horizontal, de modo que los mismos números no se traducen directamente.');
 const draw=()=>{const r=crystalRows.find(r=>r[0]===s.id),group=pointGroup(r[4],r[5]),own=group.filter(g=>det(g)>0).length;$('#catalog-detail').innerHTML='<span class="mini-label">'+r[3]+'</span><h3 class="catalog-symbol">'+r[1]+' ↔ '+r[2]+'</h3>'+stats(group)+'<p>Inversión: <strong>'+(membership(group,I)?'sí':'no')+'</strong>. Planos espejo: <strong>'+group.filter(g=>det(g)<0&&!near(g,I)&&matrixOrder(g)===2).length+'</strong>.</p><p class="helper">Subgrupo propio: '+own+' elementos. '+(own===group.length?'Todas las operaciones conservan la orientación.':'Tiene índice 2.')+'</p>';$('#catalog-poles').innerHTML=poleSVG(orbit(group,generic));document.querySelectorAll('[data-crystal]').forEach(b=>{b.classList.toggle('selected',b.dataset.crystal===s.id);b.setAttribute('aria-pressed',b.dataset.crystal===s.id);});};
 $('#system').onchange=()=>{s.system=$('#system').value;renderCatalog();$('#system').focus();};document.querySelectorAll('[data-crystal]').forEach(b=>b.onclick=()=>{s.id=b.dataset.crystal;draw();});draw();}
function colorSVG(n,k,flip){const pts=Array.from({length:n},(_,i)=>[200+115*Math.cos(i*TAU/n-Math.PI/2),167+115*Math.sin(i*TAU/n-Math.PI/2)]);let svg='<svg class="space-svg" viewBox="0 0 400 340" role="img" aria-label="Polígono de dos colores después de la operación"><title>Colores iniciales en anillos exteriores; resultado en discos interiores</title><polygon points="'+pts.map(xy).join(' ')+'" fill="none" stroke="#63708e" stroke-width="1.5"/>';for(let j=0;j<n;j++){const i=(j-k+n)%n,[x,y]=pts[j],initial=j%2,color=(i%2)^flip;svg+='<circle cx="'+x+'" cy="'+y+'" r="22" fill="none" stroke="'+palette[initial]+'" stroke-width="3"/><circle cx="'+x+'" cy="'+y+'" r="14" fill="'+palette[color]+'"/><text x="'+x+'" y="'+(y+5)+'" text-anchor="middle" fill="#131a33" font-size="13">'+(i+1)+'</text>'; }return svg+'</svg>';}
function renderColor(){const s=state.color;host.innerHTML='<div class="lab"><div class="viz"><div class="viz-header"><span>SIMETRÍA DE UN PATRÓN COLOREADO</span><span class="viz-tag">R² = E</span></div><div id="color-plot"></div><div class="viz-bottom"><span>Anillo: color original · disco: color después</span></div></div><div class="control-panel"><h3>Recupera los colores</h3>'+field('n','Grupo geométrico',[[3,'C₃ · intento de orden impar'],[4,'C₄ · cuadrado'],[6,'C₆ · hexágono']],s.n)+field('color-step','Giro Cₙᵏ',Array.from({length:s.n},(_,i)=>[i,'k = '+i+' · '+fmt(i*360/s.n)+'°']),s.k)+field('color-flip','Añadir inversión de colores',[[0,'Sin R'],[1,'Con R']],s.flip)+'<div id="color-result" aria-live="polite"></div></div></div><div class="card"><h3>Compón dos elementos de G′</h3><p class="helper">Para n par, el subgrupo H contiene las potencias pares. Las impares llevan R.</p><div id="color-products"></div><div id="color-product-result" aria-live="polite"></div></div>'+insight('R','Los giros y los colores deben respetar la misma regla de producto.','Un generador de orden impar marcado con R produce R sola al elevarlo a ese orden. Para el patrón alternado de orden par, ε(Cₙᵏ)=k módulo 2 es un homomorfismo.');
 const draw=()=>{const n=s.n,k=s.k,flip=s.flip,match=Array.from({length:n},(_,j)=>j).every(j=>(((j-k+n)%n)%2^flip)===j%2);$('#color-plot').innerHTML=colorSVG(n,k,flip);$('#color-result').innerHTML='<div class="result-box"><div class="result-equation '+(match?'pass':'fail')+'">'+(match?'Conserva el patrón':'No conserva el patrón')+'</div><p>Operación: '+(flip?'R·':'')+'C'+subs(n)+'<sup>'+k+'</sup>.</p><p>'+(n%2?'Con n impar no hay una coloración alternada cerrada alrededor del polígono. (RC'+subs(n)+')'+supers(n)+' = R.':'G′ = {potencias pares sin R, potencias impares con R}. R sola no pertenece a G′.')+'</p></div>';if(n%2){$('#color-products').innerHTML='<p class="helper">C₃ no tiene subgrupo de índice 2. El intento de etiquetar su generador con R no forma este grupo de dos colores.</p>';$('#color-product-result').innerHTML='<div class="formula">(RC₃)³=R ≠ E</div>';return;}const labels=Array.from({length:n},(_,i)=>(i===0?'E':(i%2?'R·':'')+'C'+subs(n)+supers(i)));if(s.a>=n)s.a=1;if(s.b>=n)s.b=1;$('#color-products').innerHTML='<div class="select-pair">'+field('color-a','A · segunda',labels.map((t,i)=>[i,t]),s.a)+field('color-b','B · primera',labels.map((t,i)=>[i,t]),s.b)+'</div>';const product=()=>{const a=s.a,b=s.b,c=(a+b)%n;$('#color-product-result').innerHTML='<div class="result-box"><div class="result-equation">'+labels[a]+' · '+labels[b]+' = '+labels[c]+'</div><p>Color: '+(a%2)+' ⊕ '+(b%2)+' = '+((a%2)^(b%2))+'. Giro: ('+a+'+'+b+') módulo '+n+' = '+c+'.</p></div>';};$('#color-a').onchange=()=>{s.a=Number($('#color-a').value);product();};$('#color-b').onchange=()=>{s.b=Number($('#color-b').value);product();};product();};
 $('#n').onchange=()=>{s.n=Number($('#n').value);s.k=1;renderColor();$('#n').focus();};$('#color-step').onchange=()=>{s.k=Number($('#color-step').value);draw();};$('#color-flip').onchange=()=>{s.flip=Number($('#color-flip').value);draw();};draw();}
export function renderChapter2(section,container){host=container;[renderElements,renderConjugation,renderRotations,renderLattice,renderPolyhedra,renderCyclic,renderDihedral,renderFull,renderCatalog,renderColor][section-1]();}
